; Translated from CodesCB.h - Generated automatically

Case $00 :  M_RLC(*R\BC\B\h) 
Case $01 :    M_RLC(*R\BC\B\l) 
Case $02 :  M_RLC(*R\DE\B\h) 
Case $03 :    M_RLC(*R\DE\B\l) 
Case $04 :  M_RLC(*R\HL\B\h) 
Case $05 :    M_RLC(*R\HL\B\l) 
Case $06 :  I=SafeRdZ80(*R\HL\W) : M_RLC(I) : WrZ80(*R\HL\W,I) 
Case $07 :  M_RLC(*R\AF\B\h) 
Case $08 :  M_RRC(*R\BC\B\h) 
Case $09 :    M_RRC(*R\BC\B\l) 
Case $0A :  M_RRC(*R\DE\B\h) 
Case $0B :    M_RRC(*R\DE\B\l) 
Case $0C :  M_RRC(*R\HL\B\h) 
Case $0D :    M_RRC(*R\HL\B\l) 
Case $0E :  I=SafeRdZ80(*R\HL\W) : M_RRC(I) : WrZ80(*R\HL\W,I) 
Case $0F :  M_RRC(*R\AF\B\h) 
Case $10 :  M_RL(*R\BC\B\h) 
Case $11 :    M_RL(*R\BC\B\l) 
Case $12 :  M_RL(*R\DE\B\h) 
Case $13 :    M_RL(*R\DE\B\l) 
Case $14 :  M_RL(*R\HL\B\h) 
Case $15 :    M_RL(*R\HL\B\l) 
Case $16 :  I=SafeRdZ80(*R\HL\W) : M_RL(I) : WrZ80(*R\HL\W,I) 
Case $17 :  M_RL(*R\AF\B\h) 
Case $18 :  M_RR(*R\BC\B\h) 
Case $19 :    M_RR(*R\BC\B\l) 
Case $1A :  M_RR(*R\DE\B\h) 
Case $1B :    M_RR(*R\DE\B\l) 
Case $1C :  M_RR(*R\HL\B\h) 
Case $1D :    M_RR(*R\HL\B\l) 
Case $1E :  I=SafeRdZ80(*R\HL\W) : M_RR(I) : WrZ80(*R\HL\W,I) 
Case $1F :  M_RR(*R\AF\B\h) 
Case $20 :  M_SLA(*R\BC\B\h) 
Case $21 :    M_SLA(*R\BC\B\l) 
Case $22 :  M_SLA(*R\DE\B\h) 
Case $23 :    M_SLA(*R\DE\B\l) 
Case $24 :  M_SLA(*R\HL\B\h) 
Case $25 :    M_SLA(*R\HL\B\l) 
Case $26 :  I=SafeRdZ80(*R\HL\W) : M_SLA(I) : WrZ80(*R\HL\W,I) 
Case $27 :  M_SLA(*R\AF\B\h) 
Case $28 :  M_SRA(*R\BC\B\h) 
Case $29 :    M_SRA(*R\BC\B\l) 
Case $2A :  M_SRA(*R\DE\B\h) 
Case $2B :    M_SRA(*R\DE\B\l) 
Case $2C :  M_SRA(*R\HL\B\h) 
Case $2D :    M_SRA(*R\HL\B\l) 
Case $2E :  I=SafeRdZ80(*R\HL\W) : M_SRA(I) : WrZ80(*R\HL\W,I) 
Case $2F :  M_SRA(*R\AF\B\h) 
Case $30 :  M_SLL(*R\BC\B\h) 
Case $31 :    M_SLL(*R\BC\B\l) 
Case $32 :  M_SLL(*R\DE\B\h) 
Case $33 :    M_SLL(*R\DE\B\l) 
Case $34 :  M_SLL(*R\HL\B\h) 
Case $35 :    M_SLL(*R\HL\B\l) 
Case $36 :  I=SafeRdZ80(*R\HL\W) : M_SLL(I) : WrZ80(*R\HL\W,I) 
Case $37 :  M_SLL(*R\AF\B\h) 
Case $38 :  M_SRL(*R\BC\B\h) 
Case $39 :    M_SRL(*R\BC\B\l) 
Case $3A :  M_SRL(*R\DE\B\h) 
Case $3B :    M_SRL(*R\DE\B\l) 
Case $3C :  M_SRL(*R\HL\B\h) 
Case $3D :    M_SRL(*R\HL\B\l) 
Case $3E :  I=SafeRdZ80(*R\HL\W) : M_SRL(I) : WrZ80(*R\HL\W,I) 
Case $3F :  M_SRL(*R\AF\B\h) 
Case $40 :  M_BIT(0,*R\BC\B\h) 
Case $41 :    M_BIT(0,*R\BC\B\l) 
Case $42 :  M_BIT(0,*R\DE\B\h) 
Case $43 :    M_BIT(0,*R\DE\B\l) 
Case $44 :  M_BIT(0,*R\HL\B\h) 
Case $45 :    M_BIT(0,*R\HL\B\l) 
Case $46 :  I=SafeRdZ80(*R\HL\W) : M_BIT(0,I) 
Case $47 :  M_BIT(0,*R\AF\B\h) 
Case $48 :  M_BIT(1,*R\BC\B\h) 
Case $49 :    M_BIT(1,*R\BC\B\l) 
Case $4A :  M_BIT(1,*R\DE\B\h) 
Case $4B :    M_BIT(1,*R\DE\B\l) 
Case $4C :  M_BIT(1,*R\HL\B\h) 
Case $4D :    M_BIT(1,*R\HL\B\l) 
Case $4E :  I=SafeRdZ80(*R\HL\W) : M_BIT(1,I) 
Case $4F :  M_BIT(1,*R\AF\B\h) 
Case $50 :  M_BIT(2,*R\BC\B\h) 
Case $51 :    M_BIT(2,*R\BC\B\l) 
Case $52 :  M_BIT(2,*R\DE\B\h) 
Case $53 :    M_BIT(2,*R\DE\B\l) 
Case $54 :  M_BIT(2,*R\HL\B\h) 
Case $55 :    M_BIT(2,*R\HL\B\l) 
Case $56 :  I=SafeRdZ80(*R\HL\W) : M_BIT(2,I) 
Case $57 :  M_BIT(2,*R\AF\B\h) 
Case $58 :  M_BIT(3,*R\BC\B\h) 
Case $59 :    M_BIT(3,*R\BC\B\l) 
Case $5A :  M_BIT(3,*R\DE\B\h) 
Case $5B :    M_BIT(3,*R\DE\B\l) 
Case $5C :  M_BIT(3,*R\HL\B\h) 
Case $5D :    M_BIT(3,*R\HL\B\l) 
Case $5E :  I=SafeRdZ80(*R\HL\W) : M_BIT(3,I) 
Case $5F :  M_BIT(3,*R\AF\B\h) 
Case $60 :  M_BIT(4,*R\BC\B\h) 
Case $61 :    M_BIT(4,*R\BC\B\l) 
Case $62 :  M_BIT(4,*R\DE\B\h) 
Case $63 :    M_BIT(4,*R\DE\B\l) 
Case $64 :  M_BIT(4,*R\HL\B\h) 
Case $65 :    M_BIT(4,*R\HL\B\l) 
Case $66 :  I=SafeRdZ80(*R\HL\W) : M_BIT(4,I) 
Case $67 :  M_BIT(4,*R\AF\B\h) 
Case $68 :  M_BIT(5,*R\BC\B\h) 
Case $69 :    M_BIT(5,*R\BC\B\l) 
Case $6A :  M_BIT(5,*R\DE\B\h) 
Case $6B :    M_BIT(5,*R\DE\B\l) 
Case $6C :  M_BIT(5,*R\HL\B\h) 
Case $6D :    M_BIT(5,*R\HL\B\l) 
Case $6E :  I=SafeRdZ80(*R\HL\W) : M_BIT(5,I) 
Case $6F :  M_BIT(5,*R\AF\B\h) 
Case $70 :  M_BIT(6,*R\BC\B\h) 
Case $71 :    M_BIT(6,*R\BC\B\l) 
Case $72 :  M_BIT(6,*R\DE\B\h) 
Case $73 :    M_BIT(6,*R\DE\B\l) 
Case $74 :  M_BIT(6,*R\HL\B\h) 
Case $75 :    M_BIT(6,*R\HL\B\l) 
Case $76 :  I=SafeRdZ80(*R\HL\W) : M_BIT(6,I) 
Case $77 :  M_BIT(6,*R\AF\B\h) 
Case $78 :  M_BIT(7,*R\BC\B\h) 
Case $79 :    M_BIT(7,*R\BC\B\l) 
Case $7A :  M_BIT(7,*R\DE\B\h) 
Case $7B :    M_BIT(7,*R\DE\B\l) 
Case $7C :  M_BIT(7,*R\HL\B\h) 
Case $7D :    M_BIT(7,*R\HL\B\l) 
Case $7E :  I=SafeRdZ80(*R\HL\W) : M_BIT(7,I) 
Case $7F :  M_BIT(7,*R\AF\B\h) 
Case $80 :  M_RES(0,*R\BC\B\h) 
Case $81 :    M_RES(0,*R\BC\B\l) 
Case $82 :  M_RES(0,*R\DE\B\h) 
Case $83 :    M_RES(0,*R\DE\B\l) 
Case $84 :  M_RES(0,*R\HL\B\h) 
Case $85 :    M_RES(0,*R\HL\B\l) 
Case $86 :  I=SafeRdZ80(*R\HL\W) : M_RES(0,I) : WrZ80(*R\HL\W,I) 
Case $87 :  M_RES(0,*R\AF\B\h) 
Case $88 :  M_RES(1,*R\BC\B\h) 
Case $89 :    M_RES(1,*R\BC\B\l) 
Case $8A :  M_RES(1,*R\DE\B\h) 
Case $8B :    M_RES(1,*R\DE\B\l) 
Case $8C :  M_RES(1,*R\HL\B\h) 
Case $8D :    M_RES(1,*R\HL\B\l) 
Case $8E :  I=SafeRdZ80(*R\HL\W) : M_RES(1,I) : WrZ80(*R\HL\W,I) 
Case $8F :  M_RES(1,*R\AF\B\h) 
Case $90 :  M_RES(2,*R\BC\B\h) 
Case $91 :    M_RES(2,*R\BC\B\l) 
Case $92 :  M_RES(2,*R\DE\B\h) 
Case $93 :    M_RES(2,*R\DE\B\l) 
Case $94 :  M_RES(2,*R\HL\B\h) 
Case $95 :    M_RES(2,*R\HL\B\l) 
Case $96 :  I=SafeRdZ80(*R\HL\W) : M_RES(2,I) : WrZ80(*R\HL\W,I) 
Case $97 :  M_RES(2,*R\AF\B\h) 
Case $98 :  M_RES(3,*R\BC\B\h) 
Case $99 :    M_RES(3,*R\BC\B\l) 
Case $9A :  M_RES(3,*R\DE\B\h) 
Case $9B :    M_RES(3,*R\DE\B\l) 
Case $9C :  M_RES(3,*R\HL\B\h) 
Case $9D :    M_RES(3,*R\HL\B\l) 
Case $9E :  I=SafeRdZ80(*R\HL\W) : M_RES(3,I) : WrZ80(*R\HL\W,I) 
Case $9F :  M_RES(3,*R\AF\B\h) 
Case $A0 :  M_RES(4,*R\BC\B\h) 
Case $A1 :    M_RES(4,*R\BC\B\l) 
Case $A2 :  M_RES(4,*R\DE\B\h) 
Case $A3 :    M_RES(4,*R\DE\B\l) 
Case $A4 :  M_RES(4,*R\HL\B\h) 
Case $A5 :    M_RES(4,*R\HL\B\l) 
Case $A6 :  I=SafeRdZ80(*R\HL\W) : M_RES(4,I) : WrZ80(*R\HL\W,I) 
Case $A7 :  M_RES(4,*R\AF\B\h) 
Case $A8 :  M_RES(5,*R\BC\B\h) 
Case $A9 :    M_RES(5,*R\BC\B\l) 
Case $AA :  M_RES(5,*R\DE\B\h) 
Case $AB :    M_RES(5,*R\DE\B\l) 
Case $AC :  M_RES(5,*R\HL\B\h) 
Case $AD :    M_RES(5,*R\HL\B\l) 
Case $AE :  I=SafeRdZ80(*R\HL\W) : M_RES(5,I) : WrZ80(*R\HL\W,I) 
Case $AF :  M_RES(5,*R\AF\B\h) 
Case $B0 :  M_RES(6,*R\BC\B\h) 
Case $B1 :    M_RES(6,*R\BC\B\l) 
Case $B2 :  M_RES(6,*R\DE\B\h) 
Case $B3 :    M_RES(6,*R\DE\B\l) 
Case $B4 :  M_RES(6,*R\HL\B\h) 
Case $B5 :    M_RES(6,*R\HL\B\l) 
Case $B6 :  I=SafeRdZ80(*R\HL\W) : M_RES(6,I) : WrZ80(*R\HL\W,I) 
Case $B7 :  M_RES(6,*R\AF\B\h) 
Case $B8 :  M_RES(7,*R\BC\B\h) 
Case $B9 :    M_RES(7,*R\BC\B\l) 
Case $BA :  M_RES(7,*R\DE\B\h) 
Case $BB :    M_RES(7,*R\DE\B\l) 
Case $BC :  M_RES(7,*R\HL\B\h) 
Case $BD :    M_RES(7,*R\HL\B\l) 
Case $BE :  I=SafeRdZ80(*R\HL\W) : M_RES(7,I) : WrZ80(*R\HL\W,I) 
Case $BF :  M_RES(7,*R\AF\B\h) 
Case $C0 :  M_SET(0,*R\BC\B\h) 
Case $C1 :    M_SET(0,*R\BC\B\l) 
Case $C2 :  M_SET(0,*R\DE\B\h) 
Case $C3 :    M_SET(0,*R\DE\B\l) 
Case $C4 :  M_SET(0,*R\HL\B\h) 
Case $C5 :    M_SET(0,*R\HL\B\l) 
Case $C6 :  I=SafeRdZ80(*R\HL\W) : M_SET(0,I) : WrZ80(*R\HL\W,I) 
Case $C7 :  M_SET(0,*R\AF\B\h) 
Case $C8 :  M_SET(1,*R\BC\B\h) 
Case $C9 :    M_SET(1,*R\BC\B\l) 
Case $CA :  M_SET(1,*R\DE\B\h) 
Case $CB :    M_SET(1,*R\DE\B\l) 
Case $CC :  M_SET(1,*R\HL\B\h) 
Case $CD :    M_SET(1,*R\HL\B\l) 
Case $CE :  I=SafeRdZ80(*R\HL\W) : M_SET(1,I) : WrZ80(*R\HL\W,I) 
Case $CF :  M_SET(1,*R\AF\B\h) 
Case $D0 :  M_SET(2,*R\BC\B\h) 
Case $D1 :    M_SET(2,*R\BC\B\l) 
Case $D2 :  M_SET(2,*R\DE\B\h) 
Case $D3 :    M_SET(2,*R\DE\B\l) 
Case $D4 :  M_SET(2,*R\HL\B\h) 
Case $D5 :    M_SET(2,*R\HL\B\l) 
Case $D6 :  I=SafeRdZ80(*R\HL\W) : M_SET(2,I) : WrZ80(*R\HL\W,I) 
Case $D7 :  M_SET(2,*R\AF\B\h) 
Case $D8 :  M_SET(3,*R\BC\B\h) 
Case $D9 :    M_SET(3,*R\BC\B\l) 
Case $DA :  M_SET(3,*R\DE\B\h) 
Case $DB :    M_SET(3,*R\DE\B\l) 
Case $DC :  M_SET(3,*R\HL\B\h) 
Case $DD :    M_SET(3,*R\HL\B\l) 
Case $DE :  I=SafeRdZ80(*R\HL\W) : M_SET(3,I) : WrZ80(*R\HL\W,I) 
Case $DF :  M_SET(3,*R\AF\B\h) 
Case $E0 :  M_SET(4,*R\BC\B\h) 
Case $E1 :    M_SET(4,*R\BC\B\l) 
Case $E2 :  M_SET(4,*R\DE\B\h) 
Case $E3 :    M_SET(4,*R\DE\B\l) 
Case $E4 :  M_SET(4,*R\HL\B\h) 
Case $E5 :    M_SET(4,*R\HL\B\l) 
Case $E6 :  I=SafeRdZ80(*R\HL\W) : M_SET(4,I) : WrZ80(*R\HL\W,I) 
Case $E7 :  M_SET(4,*R\AF\B\h) 
Case $E8 :  M_SET(5,*R\BC\B\h) 
Case $E9 :    M_SET(5,*R\BC\B\l) 
Case $EA :  M_SET(5,*R\DE\B\h) 
Case $EB :    M_SET(5,*R\DE\B\l) 
Case $EC :  M_SET(5,*R\HL\B\h) 
Case $ED :    M_SET(5,*R\HL\B\l) 
Case $EE :  I=SafeRdZ80(*R\HL\W) : M_SET(5,I) : WrZ80(*R\HL\W,I) 
Case $EF :  M_SET(5,*R\AF\B\h) 
Case $F0 :  M_SET(6,*R\BC\B\h) 
Case $F1 :    M_SET(6,*R\BC\B\l) 
Case $F2 :  M_SET(6,*R\DE\B\h) 
Case $F3 :    M_SET(6,*R\DE\B\l) 
Case $F4 :  M_SET(6,*R\HL\B\h) 
Case $F5 :    M_SET(6,*R\HL\B\l) 
Case $F6 :  I=SafeRdZ80(*R\HL\W) : M_SET(6,I) : WrZ80(*R\HL\W,I) 
Case $F7 :  M_SET(6,*R\AF\B\h) 
Case $F8 :  M_SET(7,*R\BC\B\h) 
Case $F9 :    M_SET(7,*R\BC\B\l) 
Case $FA :  M_SET(7,*R\DE\B\h) 
Case $FB :    M_SET(7,*R\DE\B\l) 
Case $FC :  M_SET(7,*R\HL\B\h) 
Case $FD :    M_SET(7,*R\HL\B\l) 
Case $FE :  I=SafeRdZ80(*R\HL\W) : M_SET(7,I) : WrZ80(*R\HL\W,I) 
Case $FF :  M_SET(7,*R\AF\B\h) 
