; Auto-gerado por convert_asmsx.py (descartavel, nao versionado) a partir
; de asmsx/doc/asmsx.md (manual oficial do asMSX, github.com/Fubukimaru/asMSX,
; time atual - projeto original de Eduardo "pitpan" A. Robsy Petrus). Doc ja
; e Markdown real e limpo, sem links internos - ao contrario de RedBook/
; Th2Handbook nao precisa de AnchorMap; corpo renderizado por
; GenMdHelp_RenderMarkdown (GenericMdHelpGui.pbi) direto, sem parser proprio -
; ver AsmsxHelpGui.pbi. Tabelas soltas (a de enderecos de variavel de sistema,
; secao 2.5) foram encapsuladas num fence ``` na conversao pra ficarem
; monoespacadas/legiveis (o original as deixa fora de fence).

Structure AsmsxHelpTopic
  Titulo.s
  Grupo.s
  Corpo.s
EndStructure

Global NewList AsmsxHelp_Topics.AsmsxHelpTopic()
Global AsmsxHelp_DataBuilt.b = #False
Global NewList AsmsxHelp_Scratch.s()

Procedure AsmsxHelp_Begin()
  ClearList(AsmsxHelp_Scratch())
EndProcedure

Procedure AsmsxHelp_L(Line.s)
  AddElement(AsmsxHelp_Scratch())
  AsmsxHelp_Scratch() = Line
EndProcedure

Procedure AsmsxHelp_Commit(Titulo.s, Grupo.s)
  Protected Body.s = "", First.b = #True
  ForEach AsmsxHelp_Scratch()
    If Not First : Body + #CRLF$ : EndIf
    Body + AsmsxHelp_Scratch()
    First = #False
  Next
  AddElement(AsmsxHelp_Topics())
  AsmsxHelp_Topics()\Titulo = Titulo
  AsmsxHelp_Topics()\Grupo = Grupo
  AsmsxHelp_Topics()\Corpo = Body
EndProcedure

Procedure AsmsxHelp_BuildData()
  If AsmsxHelp_DataBuilt
    ProcedureReturn
  EndIf
  AsmsxHelp_DataBuilt = #True

  AsmsxHelp_Begin()
  AsmsxHelp_L("asMSX is an assembler for the Z80 processor with a number of extensions")
  AsmsxHelp_L("to make programming for MSX easy.")
  AsmsxHelp_L("It is a cross-assembler that runs on Windows, Linux and MacOS.")
  AsmsxHelp_L("Compile time on a modern PC is near instant comparing to native MSX assemblers.")
  AsmsxHelp_L("There is no size limit on source file size.")
  AsmsxHelp_L("Source can be edited in any text editor.")
  AsmsxHelp_Commit("1.1. Description", "1. Introduction")

  AsmsxHelp_Begin()
  AsmsxHelp_L("- supports all official Z80 instructions;")
  AsmsxHelp_L("- supports all known unofficial instructions;")
  AsmsxHelp_L("- accepts standard Z80 syntax (implicit accumulator);")
  AsmsxHelp_L("- works with decimal, hexadecimal, octal and binary numbers;")
  AsmsxHelp_L("- supports arithmetic and logic operations in source code;")
  AsmsxHelp_L("- supports floating point decimal values by converting them")
  AsmsxHelp_L("  to 16-bit fixed point values;")
  AsmsxHelp_L("- math functions: trigonometric, potential etc.")
  AsmsxHelp_L("- supports multiple files through inclusion, nesting is allowed;")
  AsmsxHelp_L("- supports complete or partial direct inclusion of binary files;")
  AsmsxHelp_L("- supports local and global labels;")
  AsmsxHelp_L("- supports official MSX BIOS subroutines and")
  AsmsxHelp_L("  system variables using documented names;")
  AsmsxHelp_L("- generates binary files loadable from MSX BASIC;")
  AsmsxHelp_L("- generates ROM image files;")
  AsmsxHelp_L("- supports four MegaROM types: Konami, Konami SCC, ASCII8 and ASCII16;")
  AsmsxHelp_L("- generates COM files for MSX-DOS;")
  AsmsxHelp_L("- generates CAS files for emulators and WAV files")
  AsmsxHelp_L("  for loading on real MSX computers;")
  AsmsxHelp_L("- uses internal Assembler variables;")
  AsmsxHelp_L("- generates export symbol table (SYM);")
  AsmsxHelp_L("- writes PRINT directive messages to text file (TXT);")
  AsmsxHelp_L("- supports conditional assembly;")
  AsmsxHelp_L("- supports assembly macros;")
  AsmsxHelp_L("- integrates with BlueMSX emulator debugger.")
  AsmsxHelp_Commit("1.2. Features", "1. Introduction")

  AsmsxHelp_Begin()
  AsmsxHelp_L("asMSX project goal was to create Z80 cross assembler that is flexible,")
  AsmsxHelp_L("easy to use, reliable and designed from ground up for the development ")
  AsmsxHelp_L("of MSX ROM and MegaROM programs.")
  AsmsxHelp_L("This goal is fully achieved in current version.")
  AsmsxHelp_L("")
  AsmsxHelp_L("asMSX is a small console program that works very fast.")
  AsmsxHelp_L("It uses standard libraries present on all PCs.")
  AsmsxHelp_Commit("1.3. Project goal", "1. Introduction")

  AsmsxHelp_Begin()
  AsmsxHelp_L("asMSX implements Z80 assembly language slightly differently from standard Zilog syntax.")
  AsmsxHelp_L("Major difference is that square brackets `[ ]`,")
  AsmsxHelp_L("not parentheses `( )` are used for indirect address mode.")
  AsmsxHelp_L("This design decision allows us to support complex mathematical expressions")
  AsmsxHelp_L("that use parentheses to order evaluation precedence.")
  AsmsxHelp_L("")
  AsmsxHelp_L("asMSX supports ZILOG directive to retain source level compatibility for existing code.")
  AsmsxHelp_L("It switches indirect address mode to use parentheses.")
  AsmsxHelp_L("Mathematical expression evaluation is switched to square brackets as separators.")
  AsmsxHelp_Commit("1.4. Syntax", "1. Introduction")

  AsmsxHelp_Begin()
  AsmsxHelp_L("asMSX is a command-line program, so the easiest way to use it is from command prompt.")
  AsmsxHelp_L("To assemble a file use the following command:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```shell")
  AsmsxHelp_L("asmsx [Optional parameters] filename.asm")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("If the extension is not provided, asMSX will assume " + Chr(34) + ".asm" + Chr(34) + " as default.")
  AsmsxHelp_L("Source code files are expected to be plain 8-bit ASCII text files.")
  AsmsxHelp_L("asMSX supports text files generated on both Windows and Linux")
  AsmsxHelp_L("(CR/LF end of line or just LF).")
  AsmsxHelp_L("On Windows you can assemble a source file by dragging it to asMSX desktop icon.")
  AsmsxHelp_L("This method is not recommended, since long file name support may not work well.")
  AsmsxHelp_L("Also please try to avoid dots and other special characters in file names.")
  AsmsxHelp_L("Dot use for file extension is fine.")
  AsmsxHelp_L("")
  AsmsxHelp_L("asMSX produces messages during assembly.")
  AsmsxHelp_L("")
  AsmsxHelp_L("If no errors are encountered, following files will be generated:")
  AsmsxHelp_L("")
  AsmsxHelp_L("- **filename.sym**: text file with all the symbols defined in program with their decimal values.")
  AsmsxHelp_L("This file is compatible with BlueMSX debugger.")
  AsmsxHelp_L("You can use it to make debugging easier.")
  AsmsxHelp_L("asMSX won't generate SYM file if no constant or variable symbols were defined in program.")
  AsmsxHelp_L("- **filename.txt**: text file with messages generated by directives in program code.")
  AsmsxHelp_L("If PRINT directives are not used, file won't be generated.")
  AsmsxHelp_L("")
  AsmsxHelp_L("Depending on use of output type directives (rom/.rom, .megarom, basic, cas, wav) in your filename.asm,")
  AsmsxHelp_L("asMSX will generate one or more of the following binary files:")
  AsmsxHelp_L(" ")
  AsmsxHelp_L("- __filename.z80__: a binary file with no header;")
  AsmsxHelp_L("- __filename.bin__: a binary file that can be loaded with `BLOAD" + Chr(34) + "FILENAME.BIN" + Chr(34) + ",R` operator in MSX BASIC;")
  AsmsxHelp_L("- __filename.com__: an executable file for MSX-DOS;")
  AsmsxHelp_L("- __filename.rom__: a binary ROM or MegaROM image file;")
  AsmsxHelp_L("- __filename.cas__: a loadable tape image file for MSX emulators. `Use BLOAD" + Chr(34) + "CAS:" + Chr(34) + ",R` in MSX BASIC;")
  AsmsxHelp_L("- __filename.wav__: a 16 bit 44100Hz (CD quality) mono audio file.")
  AsmsxHelp_L("It can be loaded on real MSX computer via " + Chr(34) + "tape in" + Chr(34) + " port.")
  AsmsxHelp_L("Use `BLOAD" + Chr(34) + "CAS:" + Chr(34) + ",R` in MSX BASIC.")
  AsmsxHelp_Commit("1.5. Use", "1. Introduction")

  AsmsxHelp_Begin()
  AsmsxHelp_L("asMSX accepts the following parameters:")
  AsmsxHelp_L("")
  AsmsxHelp_L("- `-z` enable standard Z80 Zilog syntax without having .zilog directive in the")
  AsmsxHelp_L("code.")
  AsmsxHelp_L("- `-s` silent mode - suppress messages.")
  AsmsxHelp_L("- `-vv` verbose mode - print more troubleshooting messages.")
  AsmsxHelp_L("- `-r` relative path to asm file - **[DEPRECATED]** This flag is no longer needed as relative include paths now work automatically from the source file's directory.")
  AsmsxHelp_L("- -o {path or file} output to - If the path along the file is a filename")
  AsmsxHelp_L("(without extension) it will use it as output for all files (e.g. .rom, .txt and")
  AsmsxHelp_L(".sym). It can also do this inside a folder, e.g., `-o test/cookies` will produce")
  AsmsxHelp_L("a `cookies.rom` inside the `test` folder. In case it is a folder as in `test/`,")
  AsmsxHelp_L("it will put the files with the base filename on the folder `test`. Notice that")
  AsmsxHelp_L("you must always use `'\'` or `'/'` (depending if you're using linux or windows)")
  AsmsxHelp_L("always after the folder name.")
  AsmsxHelp_L("")
  AsmsxHelp_L("If you build asMSX from source with `YYDEBUG=1`, there is one more parameter available:")
  AsmsxHelp_L("")
  AsmsxHelp_L("- `-d` print bison debug messages")
  AsmsxHelp_Commit("1.5.1 Command-line parameters", "1. Introduction")

  AsmsxHelp_Begin()
  AsmsxHelp_L("If you want to build asMSX from source code,")
  AsmsxHelp_L("ensure to install the following dependencies:")
  AsmsxHelp_Commit("1.6. Build", "1. Introduction")

  AsmsxHelp_Begin()
  AsmsxHelp_L("```sh")
  AsmsxHelp_L("sudo apt install -y make gcc flex bison git build-essential \")
  AsmsxHelp_L("libbison-dev libfl-dev libpthread-stubs0-dev")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("Then you can run `make` to build from `Makefile`.")
  AsmsxHelp_L("More options are available, check the file for more information.")
  AsmsxHelp_Commit("GNU/Linux (Ubuntu based)", "1. Introduction")

  AsmsxHelp_Begin()
  AsmsxHelp_L("You can run asMSX as a Docker container available from GitHub Packages:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```sh")
  AsmsxHelp_L("docker run --rm -v $PWD:/src -w /src -u $(id -u):$(id -g) ghcr.io/fubukimaru/asmsx FILE.ASM")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("Also you can integrate asMSX in GitHub Actions Workflow by using")
  AsmsxHelp_L("the container image, useful for CI/CD processes (testing your code):")
  AsmsxHelp_L("")
  AsmsxHelp_L("```yaml")
  AsmsxHelp_L("- name: Run asMSX")
  AsmsxHelp_L("  uses: docker://ghcr.io/fubukimaru/asmsx:master")
  AsmsxHelp_L("  with:")
  AsmsxHelp_L("    args: FILE.ASM")
  AsmsxHelp_L("```")
  AsmsxHelp_Commit("1.7. Docker", "1. Introduction")

  AsmsxHelp_Begin()
  AsmsxHelp_L("asMSX accepts following line format in source code:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```")
  AsmsxHelp_L("[label:]    [directive[parameters]]    [;comments]")
  AsmsxHelp_L("[label:]    [opcode[parameters]]       [;comments]")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("Each block in brackets is optional.")
  AsmsxHelp_L("There is no limit on maximum line length.")
  AsmsxHelp_L("White space (tabs, spaces and empty lines) are ignored.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("loop:")
  AsmsxHelp_L("        ld a,[0ffffh]   ; reads the master record")
  AsmsxHelp_L("")
  AsmsxHelp_L("points:")
  AsmsxHelp_L("        db 20,30,40,50  ; points table")
  AsmsxHelp_L("")
  AsmsxHelp_L("        org 08000h      ; code offset on page 2")
  AsmsxHelp_L("        nop")
  AsmsxHelp_L("```")
  AsmsxHelp_Commit("2.1. Assembly syntax", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("Label is a symbolic name for a memory address.")
  AsmsxHelp_L("Label name should start with either a character or an underscore `_`,")
  AsmsxHelp_L("the rest could be a character or a number.")
  AsmsxHelp_L("Label name should always end with a colon `:`.")
  AsmsxHelp_L("Label name is case sensitive:")
  AsmsxHelp_L("`LABEL:` and `Label:` are treated as two separate labels.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```")
  AsmsxHelp_L("LABEL:")
  AsmsxHelp_L("Label:")
  AsmsxHelp_L("_alfanumeric:")
  AsmsxHelp_L("loop001:")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("Colon defines a label and sets its value equal to memory address of the next opcode or data value.")
  AsmsxHelp_L("If you want to get address of label, use its name without the colon.")
  AsmsxHelp_L("You can define local labels by prefixing label name with two " + Chr(34) + "at" + Chr(34) + " symbols `@@` or one " + Chr(34) + "dot" + Chr(34) + ".")
  AsmsxHelp_L("Local label name is only valid up to next global label.")
  AsmsxHelp_L("This allows to reuse label names for trivial tasks like loops,")
  AsmsxHelp_L("so you don't have to invent a bunch of different names.")
  AsmsxHelp_L("It simplifies programming and improves code readability.")
  AsmsxHelp_L("The following is valid code:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assemblyu")
  AsmsxHelp_L("Function1:")
  AsmsxHelp_L("        ...")
  AsmsxHelp_L("@@loop: ")
  AsmsxHelp_L("        ...")
  AsmsxHelp_L("Function2:")
  AsmsxHelp_L("        ...")
  AsmsxHelp_L("@@loop:")
  AsmsxHelp_L("        ...")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("OR")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("Function1:")
  AsmsxHelp_L("        ...")
  AsmsxHelp_L(".loop:	")
  AsmsxHelp_L("        ...")
  AsmsxHelp_L("Function2:")
  AsmsxHelp_L("        ...")
  AsmsxHelp_L(".loop:")
  AsmsxHelp_L("        ...")
  AsmsxHelp_L("```")
  AsmsxHelp_Commit("2.2. Labels", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("asMSX supports the following predefined labels:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```")
  AsmsxHelp_L("|--------|-------| |--------|-------| |--------|-------| |--------|-------|")
  AsmsxHelp_L("| label  | value | | label  | value | | label  | value | | label  | value |")
  AsmsxHelp_L("|--------|-------| |--------|-------| |--------|-------| |--------|-------|")
  AsmsxHelp_L("| CHKRAM | 0000h | | SETT32 | 007bh | | GTPDL  | 00deh | | SNSMAT | 0141h |")
  AsmsxHelp_L("| SYNCHR | 0008h | | SETGRP | 007eh | | TAPION | 00e1h | | PHYDIO | 0144h |")
  AsmsxHelp_L("| RDSLT  | 000ch | | SETMLT | 0081h | | TAPIN  | 00e4h | | FORMAT | 0147h |")
  AsmsxHelp_L("| CHRGTR | 0010h | | CALPAT | 0084h | | TAPIOF | 00e7h | | ISFLIO | 014ah |")
  AsmsxHelp_L("| WRSLT  | 0014h | | CALATR | 0087h | | TAPOON | 00eah | | OUTDLP | 014dh |")
  AsmsxHelp_L("| OUTDO  | 0018h | | GSPSIZ | 008ah | | TAPOUT | 00edh | | GETVCP | 0150h |")
  AsmsxHelp_L("| CALSLT | 001ch | | GRPPRT | 008dh | | TAPOOF | 00f0h | | GETVC2 | 0153h |")
  AsmsxHelp_L("| DCOMPR | 0020h | | GICINI | 0090h | | STMOTR | 00f3h | | KILBUF | 0156h |")
  AsmsxHelp_L("| ENASLT | 0024h | | WRTPSG | 0093h | | LFTQ   | 00f6h | | CALBAS | 0159h |")
  AsmsxHelp_L("| GETYPR | 0028h | | RDPSG  | 0096h | | PUTQ   | 00f9h | | SUBROM | 015ch |")
  AsmsxHelp_L("| CALLF  | 0030h | | STRTMS | 0099h | | RIGHTC | 00fch | | EXTROM | 015fh |")
  AsmsxHelp_L("| KEYINT | 0038h | | CHSNS  | 009ch | | LEFTC  | 00ffh | | CHKSLZ | 0162h |")
  AsmsxHelp_L("| INITIO | 003bh | | CHGET  | 009fh | | UPC    | 0102h | | CHKNEW | 0165h |")
  AsmsxHelp_L("| INIFNK | 003eh | | CHPUT  | 00a2h | | TUPC   | 0105h | | EOL    | 0168h |")
  AsmsxHelp_L("| DISSCR | 0041h | | LPTOUT | 00a5h | | DOWNC  | 0108h | | BIGFIL | 016bh |")
  AsmsxHelp_L("| ENASCR | 0044h | | LPTSTT | 00a8h | | TDOWNC | 010bh | | NSETRD | 016eh |")
  AsmsxHelp_L("| WRTVDP | 0047h | | CNVCHR | 00abh | | SCALXY | 010eh | | NSTWRT | 0171h |")
  AsmsxHelp_L("| RDVRM  | 004ah | | PINLIN | 00aeh | | MAPXYC | 0111h | | NRDVRM | 0174h |")
  AsmsxHelp_L("| WRTVRM | 004dh | | INLIN  | 00b1h | | FETCHC | 0114h | | NWRVRM | 0177h |")
  AsmsxHelp_L("| SETRD  | 0050h | | QINLIN | 00b4h | | STOREC | 0117h | | RDBTST | 017ah |")
  AsmsxHelp_L("| SETWRT | 0053h | | BREAKX | 00b7h | | SETATR | 011ah | | WRBTST | 017dh |")
  AsmsxHelp_L("| FILVRM | 0056h | | ISCNTC | 00bah | | READC  | 011dh | | CHGCPU | 0180h |")
  AsmsxHelp_L("| LDIRMV | 0059h | | CKCNTC | 00bdh | | SETC   | 0120h | | GETCPU | 0183h |")
  AsmsxHelp_L("| LDIRVM | 005ch | | BEEP   | 00c0h | | NSETCX | 0123h | | PCMPLY | 0186h |")
  AsmsxHelp_L("| CHGMOD | 005fh | | CLS    | 00c3h | | GTASPC | 0126h | | PCMREC | 0189h |")
  AsmsxHelp_L("| CHGCLR | 0062h | | POSIT  | 00c6h | | PNTINI | 0129h | |--------|-------|")
  AsmsxHelp_L("| NMI    | 0066h | | FNKSB  | 00c9h | | SCANR  | 012ch | ")
  AsmsxHelp_L("| CLRSPR | 0069h | | ERAFNK | 00cch | | SCANL  | 012fh | ")
  AsmsxHelp_L("| INITXT | 006ch | | DSPFNK | 00cfh | | CHGCAP | 0132h | ")
  AsmsxHelp_L("| INIT32 | 006fh | | TOTEXT | 00d2h | | CHGSND | 0135h | ")
  AsmsxHelp_L("| INIGRP | 0072h | | GTSTCK | 00d5h | | RSLREG | 0138h | ")
  AsmsxHelp_L("| INIMLT | 0075h | | GTTRIG | 00d8h | | WSLREG | 013bh | ")
  AsmsxHelp_L("| SETTXT | 0078h | | GTPAD  | 00dbh | | RDVDP  | 013eh | ")
  AsmsxHelp_L("|--------|-------| |--------|-------| |--------|-------|")
  AsmsxHelp_L("```")
  AsmsxHelp_Commit("2.2.1. Predefined labels", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("A numeric expression is a number or a result of operation on numbers.")
  AsmsxHelp_Commit("2.3. Numeric expression", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("There are several popular numeric systems (radices, plural form of radix).")
  AsmsxHelp_L("Here are a few examples of syntax for such systems:")
  AsmsxHelp_Commit("2.3.1. Numeric formats", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("Radix 10 numbers are usually expressed as")
  AsmsxHelp_L("a group of one or more decimal digits.")
  AsmsxHelp_L("The only restriction is that you must explicitly express zeroes.")
  AsmsxHelp_L("This is the numeric system that people use in everyday life.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("0 10 25 1 255 2048")
  AsmsxHelp_L("```")
  AsmsxHelp_Commit("DECIMAL INTEGER", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("A decimal number with dot separating integer from fraction.")
  AsmsxHelp_L("Syntax requires dot to be present for the constant to be recognized as a floating point value.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("3.14 1.25 0.0 32768.0 -0.50 15.2")
  AsmsxHelp_L("```")
  AsmsxHelp_Commit("DECIMAL FLOATING POINT", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("Radix 8 numbers can be specified using two conventions.")
  AsmsxHelp_L("")
  AsmsxHelp_L("- C, C++ and Java convention:")
  AsmsxHelp_L("The number starts with `0` and continues with octal digits `0`..`7`.")
  AsmsxHelp_L("")
  AsmsxHelp_L("- The second convention is native to assemblers,")
  AsmsxHelp_L("and is a number with octal digits followed by letter `o`, lowercase or uppercase.")
  AsmsxHelp_L("Second mode is included for compatibility, but is not recommended.")
  AsmsxHelp_L("Upper case letter `O` is easy to confuse with number zero `0`.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("01 077 010 1o 77o 10o")
  AsmsxHelp_L("```")
  AsmsxHelp_Commit("OCTAL", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("Radix 16 numbers, very popular in assembly programming.")
  AsmsxHelp_L("They can be specified using three different conventions.")
  AsmsxHelp_L("")
  AsmsxHelp_L("- C, C++ and Java convention: a number that starts with `0x` prefix and")
  AsmsxHelp_L("continues with one or more hexadecimal digits: `0`..`9`, `a`..`f` or `A`..`F`.")
  AsmsxHelp_L("")
  AsmsxHelp_L("- Second convention is borrowed from Pascal: a group of hexadecimal digits prefixed with `$`.")
  AsmsxHelp_L("")
  AsmsxHelp_L("- The third convention is native to assemblers:")
  AsmsxHelp_L("a group of hexadecimal digits, followed by letter `h` or `H`.  ")
  AsmsxHelp_L("This convention requires first digit to always be numeric.")
  AsmsxHelp_L("If a hexadecimal number starts with letter, you should prefix the number with `0`.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("0x8a 0xff 0x10")
  AsmsxHelp_L("$8a $ff $10")
  AsmsxHelp_L("8ah 0ffh 10h")
  AsmsxHelp_L("```")
  AsmsxHelp_Commit("HEXADECIMAL", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("Radix 2 numbers are specified as a group of")
  AsmsxHelp_L("binary digits `0` and `1`, followed by letter `b` or `B`.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("1000000b 11110000b 0010101b 1001b")
  AsmsxHelp_L("```")
  AsmsxHelp_Commit("BINARY", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("Numeric expressions use operators on numbers in supported numeric systems.")
  AsmsxHelp_L("Common notation is used for typical arithmetic operators:")
  AsmsxHelp_L("")
  AsmsxHelp_L("- `+` addition;")
  AsmsxHelp_L("- `-` subtraction;")
  AsmsxHelp_L("- `*` multiplication;")
  AsmsxHelp_L("- `/` division;")
  AsmsxHelp_L("- `%` modulus (integer remainder from division);")
  AsmsxHelp_L("")
  AsmsxHelp_L("Less common operators borrow from C/C++:")
  AsmsxHelp_L("")
  AsmsxHelp_L("- `<<` left bit shift: shifts specified number of bits left.")
  AsmsxHelp_L("It is equivalent to a number of multiplications by 2;")
  AsmsxHelp_L("- `>>` right bit shift: shifts specified number of bits right.")
  AsmsxHelp_L("It is equivalent to a number of divisions by 2;")
  AsmsxHelp_L("- `|` bit-level OR;")
  AsmsxHelp_L("- `&` bit-level AND;")
  AsmsxHelp_L("- `^` bit-level XOR;")
  AsmsxHelp_L("- `NOT` unary negation;")
  AsmsxHelp_L("- `~` logical negation: returns complementing binary number;")
  AsmsxHelp_L("- `||` logical OR;")
  AsmsxHelp_L("- `&&` logical AND;")
  AsmsxHelp_L("- `==` logical equivalent;")
  AsmsxHelp_L("- `!=` logical non-equivalent;")
  AsmsxHelp_L("- `<`  less-than;")
  AsmsxHelp_L("- `<=` less-then or equal;")
  AsmsxHelp_L("- `>`  greater-then;")
  AsmsxHelp_L("- `>=` greater-then or equal.")
  AsmsxHelp_L("")
  AsmsxHelp_L("The precedence order is same as in C/C++.")
  AsmsxHelp_L("Parentheses can be used to explicitly specify")
  AsmsxHelp_L("parsing precedence in arithmetic expressions.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```python")
  AsmsxHelp_L("((2*8)/(1+3))<<2")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("Same rules apply to all numbers, including non decimal.")
  AsmsxHelp_L("Additionally following functions are supported:")
  AsmsxHelp_L("")
  AsmsxHelp_L("- `SIN(X)`   sine function, takes input in radians;")
  AsmsxHelp_L("- `COS(X)`   cosine;")
  AsmsxHelp_L("- `TAN(X)`   tangent;")
  AsmsxHelp_L("- `ACOS(X)`  arccosine;")
  AsmsxHelp_L("- `ASIN(X)`  arcsine;")
  AsmsxHelp_L("- `ATAN(X)`  arctangent;")
  AsmsxHelp_L("- `SQR(X)`   square;")
  AsmsxHelp_L("- `SQRT(X)`  square root;")
  AsmsxHelp_L("- `EXP(X)`   exponential value of X;")
  AsmsxHelp_L("- `POW(X,Y)` returns X raised to the power Y;")
  AsmsxHelp_L("- `LOG(X)`   logarithm;")
  AsmsxHelp_L("- `LN(X)`    natural logarithm;")
  AsmsxHelp_L("- `ABS(X)`   returns the absolute value of X.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`PI` is predefined as a double precision floating point constant.")
  AsmsxHelp_L("It can be used in numeric expressions.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```python")
  AsmsxHelp_L("sin(pi*45.0/180.0)")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("It is useful to support non-integer values in Z80 assembler programs")
  AsmsxHelp_L("by providing simple floating to fixed point conversion mechanism.")
  AsmsxHelp_L("This is done using two conversion functions:")
  AsmsxHelp_L("")
  AsmsxHelp_L("- `FIX(X)`      convert floating point value to fixed point;")
  AsmsxHelp_L("- `FIXMUL(X,Y)` multiply two fixed point numbers;")
  AsmsxHelp_L("- `FIXDIV(X,Y)` divide X by Y;")
  AsmsxHelp_L("- `INT(X)`      convert a non-integer value to integer.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`$` is is a special read-only variable.")
  AsmsxHelp_L("During assembly of program, `$` is replaced with memory address of next opcode or data,")
  AsmsxHelp_L("during execution it is equal to `PC` register.")
  AsmsxHelp_Commit("2.3.2. Operators", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("You can include data in your assembler program using four different directives:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("db data,[data...]")
  AsmsxHelp_L("defb data,[data...]")
  AsmsxHelp_L("dt " + Chr(34) + "text" + Chr(34) + "")
  AsmsxHelp_L("deft " + Chr(34) + "text" + Chr(34) + "")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("These instructions define data as 8-bit byte values. dt was included for")
  AsmsxHelp_L("compatibility with other Z80 assemblers. All four directives are equivalent.")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("dw data,[data...]")
  AsmsxHelp_L("defw data,[data...]")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("This will define 16-bit word data.")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("ds X")
  AsmsxHelp_L("defs X")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("This will reserve X bytes in memory starting with current memory address.")
  AsmsxHelp_L("")
  AsmsxHelp_L("Special predefined directives are available for reserving memory for variables")
  AsmsxHelp_L("of conventional sizes, such as byte and word:")
  AsmsxHelp_L("")
  AsmsxHelp_L("- `.byte` reserve one byte of space (8 bits);")
  AsmsxHelp_L("- `.word` reserve one word of space, which is equivalent to two bytes (16 bits).")
  AsmsxHelp_Commit("2.4. Data definition", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("Directives are predefined instructions that help control the code and enable")
  AsmsxHelp_L("additional asMSX features.")
  AsmsxHelp_L("**Remember, you can use them without first point character.**")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.ZILOG` This directive will switch the use of square brackets and parentheses")
  AsmsxHelp_L("from the point it is defined on. Parentheses will be used for " + Chr(34) + "memory content")
  AsmsxHelp_L("at" + Chr(34) + " indirection and brackets to group operations in complex arithmetic")
  AsmsxHelp_L("expressions.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.ORG X` This directive is used to force current memory address offset. All")
  AsmsxHelp_L("subsequent code will be assembled from that offset on.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.PAGE X` This directive is similar to `.ORG` directive, but instead of bytes,")
  AsmsxHelp_L("offset is defined in page blocks (16KB). `.PAGE 0` is equivalent to `.ORG 0000h`,")
  AsmsxHelp_L("`.PAGE 1` is same as `.ORG 4000h`, `.PAGE 2` is same as `.ORG 8000h` and `.PAGE 3` is")
  AsmsxHelp_L("same as `.ORG 0C000h`.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.EQU`  This directive is used to define constants. Naming rules are mostly the")
  AsmsxHelp_L("same as for labels. There are no local constants.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`Variable = expression` asMSX can use integer variables. Variables must be")
  AsmsxHelp_L("initialized by assigning them an integer values. It is possible to perform")
  AsmsxHelp_L("arithmetic operations with variables.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("Value1=0")
  AsmsxHelp_L("Value1=Value1+1")
  AsmsxHelp_L("ld a,Value1")
  AsmsxHelp_L("Value1=Value1*2")
  AsmsxHelp_L("ld b,Value1")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.BIOS` Predefined call address for common BIOS routines, including those")
  AsmsxHelp_L("specified in the MSX, MSX2, MSX2+ and Turbo-R standards. The usual names are")
  AsmsxHelp_L("used in upper case. Can be found in asMSX code at the function `msx_bios()` in")
  AsmsxHelp_L("`dura.y`.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.BIOSVARS` Predefined system variables. The list of variables is the following:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```")
  AsmsxHelp_L("| Name   | Address |")
  AsmsxHelp_L("| :---   |    ---: |")
  AsmsxHelp_L("| CGTABL |   $0004 |")
  AsmsxHelp_L("| VDP_DR |   $0006 |")
  AsmsxHelp_L("| VDP_DW |   $0007 |")
  AsmsxHelp_L("| MSXID1 |   $002b |")
  AsmsxHelp_L("| MSXID2 |   $002c |")
  AsmsxHelp_L("| MSXID3 |   $002d |")
  AsmsxHelp_L("| RDPRIM |   $f380 |")
  AsmsxHelp_L("| WRPRIM |   $f385 |")
  AsmsxHelp_L("| CLPRIM |   $f38c |")
  AsmsxHelp_L("| LINL40 |   $f3ae |")
  AsmsxHelp_L("| LINL32 |   $f3af |")
  AsmsxHelp_L("| LINLEN |   $f3b0 |")
  AsmsxHelp_L("| CRTCNT |   $f3b1 |")
  AsmsxHelp_L("| CLMLST |   $f3b2 |")
  AsmsxHelp_L("| TXTNAM |   $f3b3 |")
  AsmsxHelp_L("| TXTCOL |   $f3b5 |")
  AsmsxHelp_L("| TXTCGP |   $f3b7 |")
  AsmsxHelp_L("| TXTATR |   $f3b9 |")
  AsmsxHelp_L("| TXTPAT |   $f3bb |")
  AsmsxHelp_L("| T32NAM |   $f3bd |")
  AsmsxHelp_L("| T32COL |   $f3bf |")
  AsmsxHelp_L("| T32CGP |   $f3c1 |")
  AsmsxHelp_L("| T32ATR |   $f3c3 |")
  AsmsxHelp_L("| T32PAT |   $f3c5 |")
  AsmsxHelp_L("| GRPNAM |   $f3c7 |")
  AsmsxHelp_L("| GRPCOL |   $f3c9 |")
  AsmsxHelp_L("| GRPCGP |   $f3cb |")
  AsmsxHelp_L("| GRPATR |   $f3cd |")
  AsmsxHelp_L("| GRPPAT |   $f3cf |")
  AsmsxHelp_L("| MLTNAM |   $f3d1 |")
  AsmsxHelp_L("| MLTCOL |   $f3d3 |")
  AsmsxHelp_L("| MLTCGP |   $f3d5 |")
  AsmsxHelp_L("| MLTATR |   $f3d7 |")
  AsmsxHelp_L("| MLTPAT |   $f3d9 |")
  AsmsxHelp_L("| CLIKSW |   $f3db |")
  AsmsxHelp_L("| CSRY   |   $f3dc |")
  AsmsxHelp_L("| CSRX   |   $f3dd |")
  AsmsxHelp_L("| CNSDFG |   $f3de |")
  AsmsxHelp_L("| RG0SAV |   $f3df |")
  AsmsxHelp_L("| RG1SAV |   $f3e0 |")
  AsmsxHelp_L("| RG2SAV |   $f3e1 |")
  AsmsxHelp_L("| RG3SAV |   $f3e2 |")
  AsmsxHelp_L("| RG4SAV |   $f3e3 |")
  AsmsxHelp_L("| RG5SAV |   $f3e4 |")
  AsmsxHelp_L("| RG6SAV |   $f3e5 |")
  AsmsxHelp_L("| RG7SAV |   $f3e6 |")
  AsmsxHelp_L("| STATFL |   $f3e7 |")
  AsmsxHelp_L("| TRGFLG |   $f3e8 |")
  AsmsxHelp_L("| FORCLR |   $f3e9 |")
  AsmsxHelp_L("| BAKCLR |   $f3ea |")
  AsmsxHelp_L("| BDRCLR |   $f3eb |")
  AsmsxHelp_L("| MAXUPD |   $f3ec |")
  AsmsxHelp_L("| MINUPD |   $f3ef |")
  AsmsxHelp_L("| ATRBYT |   $f3f2 |")
  AsmsxHelp_L("| QUEUES |   $f3f3 |")
  AsmsxHelp_L("| FRCNEW |   $f3f5 |")
  AsmsxHelp_L("| SCNCNT |   $f3f6 |")
  AsmsxHelp_L("| REPCNT |   $f3f7 |")
  AsmsxHelp_L("| PUTPNT |   $f3f8 |")
  AsmsxHelp_L("| GETPNT |   $f3fa |")
  AsmsxHelp_L("| CS120  |   $f3fc |")
  AsmsxHelp_L("| CS240  |   $f401 |")
  AsmsxHelp_L("| LOW    |   $f406 |")
  AsmsxHelp_L("| HIGH   |   $f408 |")
  AsmsxHelp_L("| HEADER |   $f40a |")
  AsmsxHelp_L("| ASPCT1 |   $f40b |")
  AsmsxHelp_L("| ASPCT2 |   $f40d |")
  AsmsxHelp_L("| ENDPRG |   $f40f |")
  AsmsxHelp_L("| ERRFLG |   $f414 |")
  AsmsxHelp_L("| LPTPOS |   $f415 |")
  AsmsxHelp_L("| PRTFLG |   $f416 |")
  AsmsxHelp_L("| NTMSXP |   $f417 |")
  AsmsxHelp_L("| RAWPRT |   $f418 |")
  AsmsxHelp_L("| VLZADR |   $f419 |")
  AsmsxHelp_L("| VLZDAT |   $f41b |")
  AsmsxHelp_L("| CURLIN |   $f41c |")
  AsmsxHelp_L("| EXBRSA |   $faf8 |")
  AsmsxHelp_L("| PRSCNT |   $fb35 |")
  AsmsxHelp_L("| SAVSP  |   $fb36 |")
  AsmsxHelp_L("| VOICEN |   $fb38 |")
  AsmsxHelp_L("| SAVVOL |   $fb39 |")
  AsmsxHelp_L("| MCLLEN |   $fb3b |")
  AsmsxHelp_L("| MCLPTR |   $fb3c |")
  AsmsxHelp_L("| QUEUEN |   $fb3e |")
  AsmsxHelp_L("| MUSICF |   $fb3f |")
  AsmsxHelp_L("| PLYCNT |   $fb40 |")
  AsmsxHelp_L("| VCBA   |   $fb41 |")
  AsmsxHelp_L("| VCBB   |   $fb66 |")
  AsmsxHelp_L("| VCBC   |   $fb8b |")
  AsmsxHelp_L("| ENSTOP |   $fbb0 |")
  AsmsxHelp_L("| BASROM |   $fbb1 |")
  AsmsxHelp_L("| LINTTB |   $fbb2 |")
  AsmsxHelp_L("| FSTPOS |   $fbca |")
  AsmsxHelp_L("| CODSAV |   $fbcc |")
  AsmsxHelp_L("| FNKSWI |   $fbcd |")
  AsmsxHelp_L("| FNKFLG |   $fbce |")
  AsmsxHelp_L("| ONGSBF |   $fbd8 |")
  AsmsxHelp_L("| CLIKFL |   $fbd9 |")
  AsmsxHelp_L("| OLDKEY |   $fbda |")
  AsmsxHelp_L("| NEWKEY |   $fbe5 |")
  AsmsxHelp_L("| KEYBUF |   $fbf0 |")
  AsmsxHelp_L("| BUFEND |   $fc18 |")
  AsmsxHelp_L("| LINWRK |   $fc18 |")
  AsmsxHelp_L("| PATWRK |   $fc40 |")
  AsmsxHelp_L("| BOTTOM |   $fc48 |")
  AsmsxHelp_L("| HIMEM  |   $fc4a |")
  AsmsxHelp_L("| TRPTBL |   $fc4c |")
  AsmsxHelp_L("| RTYCNT |   $fc9a |")
  AsmsxHelp_L("| INTFLG |   $fc9b |")
  AsmsxHelp_L("| PADY   |   $fc9c |")
  AsmsxHelp_L("| PADX   |   $fc9d |")
  AsmsxHelp_L("| JIFFY  |   $fc9e |")
  AsmsxHelp_L("| INTVAL |   $fca0 |")
  AsmsxHelp_L("| INTCNT |   $fca2 |")
  AsmsxHelp_L("| LOWLIM |   $fca4 |")
  AsmsxHelp_L("| WINWID |   $fca5 |")
  AsmsxHelp_L("| GRPHED |   $fca6 |")
  AsmsxHelp_L("| ESCCNT |   $fca7 |")
  AsmsxHelp_L("| INSFLG |   $fca8 |")
  AsmsxHelp_L("| CSRSW  |   $fca9 |")
  AsmsxHelp_L("| CSTYLE |   $fcaa |")
  AsmsxHelp_L("| CAPST  |   $fcab |")
  AsmsxHelp_L("| KANAST |   $fcac |")
  AsmsxHelp_L("| KANAMD |   $fcad |")
  AsmsxHelp_L("| FLBMEM |   $fcae |")
  AsmsxHelp_L("| SCRMOD |   $fcaf |")
  AsmsxHelp_L("| OLDSCR |   $fcb0 |")
  AsmsxHelp_L("| CASPRV |   $fcb1 |")
  AsmsxHelp_L("| BRDATR |   $fcb2 |")
  AsmsxHelp_L("| GXPOS  |   $fcb3 |")
  AsmsxHelp_L("| GYPOS  |   $fcb5 |")
  AsmsxHelp_L("| GRPACX |   $fcb7 |")
  AsmsxHelp_L("| GRPACY |   $fcb9 |")
  AsmsxHelp_L("| DRWFLG |   $fcbb |")
  AsmsxHelp_L("| DRWSCL |   $fcbc |")
  AsmsxHelp_L("| DRWANG |   $fcbd |")
  AsmsxHelp_L("| RUNBNF |   $fcbe |")
  AsmsxHelp_L("| SAVENT |   $fcbf |")
  AsmsxHelp_L("| EXPTBL |   $fcc1 |")
  AsmsxHelp_L("| SLTTBL |   $fcc5 |")
  AsmsxHelp_L("| SLTATR |   $fcc9 |")
  AsmsxHelp_L("| SLTWRK |   $fd09 |")
  AsmsxHelp_L("| PROCNM |   $fd89 |")
  AsmsxHelp_L("| DEVICE |   $fd99 |")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("More information can be found in [Grauw's listing](http://map.grauw.nl/resources/msxsystemvars.php).")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.ROM` Indicates that a ROM header should be generated. It is important to use")
  AsmsxHelp_L(".PAGE directive first to define start address. .START directive can be used to")
  AsmsxHelp_L("indicate the start address for the program and it should be used *before* the")
  AsmsxHelp_L(".ROM directive. Use this directive **after** relocating the program counter with")
  AsmsxHelp_L(".ORG or .PAGE directives. This is needed as ROM will write the header of the ROM")
  AsmsxHelp_L("which is already ROM data.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.MegaROM [mapper]` Generates header for specified MegaROM mapper. This")
  AsmsxHelp_L("directive will also set start address to sub-page 0 of selected mapper, so")
  AsmsxHelp_L("using `ORG`, `PAGE` or `SUBPAGE` directives is not necessary.")
  AsmsxHelp_L("Supported mapper types are:")
  AsmsxHelp_L("")
  AsmsxHelp_L("- `Konami`: sub-page size is 8 KB, up to 32 sub-pages.")
  AsmsxHelp_L("Maximum MegaROM size is 256 KB (2 megabits).")
  AsmsxHelp_L("Page 1 (4000h - 5FFFh) should be mapped to MegaROM")
  AsmsxHelp_L("sup-page 0 and should not be changed while the program runs.")
  AsmsxHelp_L("")
  AsmsxHelp_L("- `KonamiSCC`: sub-page size is 8 KB, up to 64 sub-pages.")
  AsmsxHelp_L("Maximum MegaROM size is 512 KB (4 megabits).")
  AsmsxHelp_L("Supports access to SCC, Konami Sound Custom Chip.")
  AsmsxHelp_L("")
  AsmsxHelp_L("- `ASCII8`: sub-page size is 8 KB, up to 256 sub-pages.")
  AsmsxHelp_L("Maximum MegaROM size is 2048 KB (16 megabits, 2 megabytes).")
  AsmsxHelp_L("")
  AsmsxHelp_L("- `ASCII16`: sub-page size is 16 KB, up to 256 sub-pages.")
  AsmsxHelp_L("Maximum MegaROM size is 4096 KB (32 megabits, 4 megabytes).")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.BASIC` Generates the header for a loadable binary MSX-BASIC file. It is")
  AsmsxHelp_L("important to use .ORG directive to indicate the intended start address for the")
  AsmsxHelp_L("program. Use .START directive if execution entry point is not at the start of")
  AsmsxHelp_L("program. The default extension of the output file is BIN.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.MSXDOS` Produces a COM executable for MSX-DOS. No need for .ORG directive,")
  AsmsxHelp_L("because COM files are always loaded at 0100h.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.START X` Indicates the starting execution address for ROM, MegaROM and BIN")
  AsmsxHelp_L("files, if it is not at the beginning of the file. Use it before any .ROM-like")
  AsmsxHelp_L("directive.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.SEARCH` For ROMs and MegaROMs to that start on page 1 (4000h),")
  AsmsxHelp_L("it automatically finds and sets slot and subslot on page 2 (8000h).")
  AsmsxHelp_L("It is equivalent to the following code:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("call 0138h ;RSLREG")
  AsmsxHelp_L("rrca")
  AsmsxHelp_L("rrca")
  AsmsxHelp_L("and 03h")
  AsmsxHelp_L("")
  AsmsxHelp_L("; Secondary Slot")
  AsmsxHelp_L("ld c,a")
  AsmsxHelp_L("ld hl,0FCC1h")
  AsmsxHelp_L("add a,l")
  AsmsxHelp_L("ld l,a")
  AsmsxHelp_L("ld a,[hl]")
  AsmsxHelp_L("and 80h")
  AsmsxHelp_L("or c")
  AsmsxHelp_L("ld c,a")
  AsmsxHelp_L("inc l")
  AsmsxHelp_L("inc l")
  AsmsxHelp_L("inc l")
  AsmsxHelp_L("inc l")
  AsmsxHelp_L("ld a,[hl]")
  AsmsxHelp_L("")
  AsmsxHelp_L("; Define slot ID")
  AsmsxHelp_L("and 0ch")
  AsmsxHelp_L("or c")
  AsmsxHelp_L("ld h,80h")
  AsmsxHelp_L("")
  AsmsxHelp_L("; Enable")
  AsmsxHelp_L("call 0024h ;ENASLT")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.SUBPAGE n AT X` This macro is used to define different sub-pages in a MegaROM.")
  AsmsxHelp_L("In MegaROM code generation model of asMSX, all code and data is included in")
  AsmsxHelp_L("sub-pages, equivalent to logic blocks that mapper operated with. You must")
  AsmsxHelp_L("provide the number of sub-page and execution entry point.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.SELECT n AT x` / `.SELECT record AT x` Just like above, this macro selects the")
  AsmsxHelp_L("sub-page n with execution entry point at x. Specific code that end up being")
  AsmsxHelp_L("used for this directive depends on selected MegaROM mapper type. It doesn't")
  AsmsxHelp_L("change the value of any record or affect interrupt mode or status flags.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.PHASE X` / `.DEPHASE` These two routines enable virtual memory use. Instructions")
  AsmsxHelp_L("will be assembled to be stored at one memory address, but ready to be executed")
  AsmsxHelp_L("from another memory address. This is useful for creation of code in ROM image,")
  AsmsxHelp_L("that is copied to RAM and then executed. The effect is that label values will")
  AsmsxHelp_L("be calculated for supplied address. .DEPHASE reverts assembler behaviour to")
  AsmsxHelp_L("normal, although ORG, PAGE or SUBPAGE will have the same effect.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.CALLBIOS X` Calls a BIOS routine from MSX-DOS program. It is equivalent to")
  AsmsxHelp_L("following code:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("LD IY,[EXPTBL-1]")
  AsmsxHelp_L("LD IX,ROUTINE")
  AsmsxHelp_L("CALL CALSLT")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.CALLDOS X` Calls MSX-DOS function. It is equivalent to following code:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("LD C,CODE")
  AsmsxHelp_L("CALL 0005h")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.SIZE X` Sets the output file size in Kilobytes.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.INCLUDE " + Chr(34) + "file" + Chr(34) + "` Includes source code from an external file.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.INCBIN " + Chr(34) + "file" + Chr(34) + " [SKIP X] [SIZE Y]` Injects the contents of a binary file into")
  AsmsxHelp_L("program. Optional SIZE and SKIP parameters allow to include a number of bytes,")
  AsmsxHelp_L("starting at specified offset.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.RANDOM(n)` Generates a random integer number from the range of 0 to n-1.")
  AsmsxHelp_L("Provides better entropy than the Z80 R register.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.DEBUG " + Chr(34) + "text" + Chr(34) + "` Adds text to assembled program that is visible during debugging,")
  AsmsxHelp_L("but does not affect the execution. BlueMSX debugger supports this extended")
  AsmsxHelp_L("functionality.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.BREAK [X]` / `.BREAKPOINT [X]` Defines a breakpoint for BlueMSX debugger. It")
  AsmsxHelp_L("doesn't affect the execution, but it should be removed from the final build. If")
  AsmsxHelp_L("the direction is not indicated, the breakpoint will be executed in the position")
  AsmsxHelp_L("in which it has been defined.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`REPT n` / `ENDR` This macro allows you to repeat  a block given number of times.")
  AsmsxHelp_L("Nesting allows generation of complex tables. There is a restriction: the number")
  AsmsxHelp_L("of repetitions must be defined as integer number, it can't be calculated from a")
  AsmsxHelp_L("numeric expression.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("REPT 16")
  AsmsxHelp_L("  OUTI")
  AsmsxHelp_L("ENDR")
  AsmsxHelp_L("")
  AsmsxHelp_L("X=0")
  AsmsxHelp_L("Y=0")
  AsmsxHelp_L("REPT 10")
  AsmsxHelp_L("  REPT 10")
  AsmsxHelp_L("    DB X*Y")
  AsmsxHelp_L("    X=X+1")
  AsmsxHelp_L("  ENDR")
  AsmsxHelp_L("  Y=Y+1")
  AsmsxHelp_L("ENDR")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.PRINTTEXT " + Chr(34) + "text" + Chr(34) + "` / `.PRINTSTRING " + Chr(34) + "text" + Chr(34) + "` Prints a text in the output text file.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.PRINT expression` / `.PRINTDEC` Prints a numeric expression in decimal format.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.PRINTHEX expression` Prints a numeric expression in hexadecimal format.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.PRINTFIX expression` Prints a fixed-point numeric value.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.CAS [" + Chr(34) + "text" + Chr(34) + "]` / `.CASSETTE [" + Chr(34) + "text" + Chr(34) + "]` Generates a tape file name in output file.")
  AsmsxHelp_L("This only works if output file type is loadable BASIC program, ROM in page 2 or")
  AsmsxHelp_L("Z80 binary blob without header. Supplied name can be used to load the program")
  AsmsxHelp_L("from the tape, maximum length is 6 characters. If not explicitly specified, it")
  AsmsxHelp_L("is set to name of output file.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.WAV [" + Chr(34) + "text" + Chr(34) + "]` Like the previous command, but instead of CAS file, it generates")
  AsmsxHelp_L("a WAV audio file that can be loaded directly on a real MSX through tape-in")
  AsmsxHelp_L("port.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.FILENAME [" + Chr(34) + "text" + Chr(34) + "]` Using this directive will set the name of the output file.")
  AsmsxHelp_L("If not explicitly specified, source file name will be used, plus appropriate")
  AsmsxHelp_L("extension.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`.SINCLAIR` :warning: **Currently broken** ")
  AsmsxHelp_L("This directive sets the output file type to TAP format with appropriate header.")
  AsmsxHelp_L("It is intended for loading on ZX Spectrum emulators or real")
  AsmsxHelp_L("hardware if you have a working playback application.")
  AsmsxHelp_Commit("2.5. Directives", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("It is highly recommended to use comments throughout the assembler source code.")
  AsmsxHelp_L("asMSX supports comments in a variety of formats:")
  AsmsxHelp_L("")
  AsmsxHelp_L("    ; Comment")
  AsmsxHelp_L("")
  AsmsxHelp_L("Single line comment. This is the standard for assembler listings. Entire line")
  AsmsxHelp_L("up to carriage return is ignored.")
  AsmsxHelp_L("")
  AsmsxHelp_L("    // Comment")
  AsmsxHelp_L("")
  AsmsxHelp_L("Same as above. Two consecutive slashes is a convention from C++ and C since")
  AsmsxHelp_L("C99.")
  AsmsxHelp_L("")
  AsmsxHelp_L("    /* Comments */")
  AsmsxHelp_L("    { Comments }")
  AsmsxHelp_L("	")
  AsmsxHelp_L("C/C++ and Pascal style multi line comments. All text between the delimiters")
  AsmsxHelp_L("is skipped during assembly.")
  AsmsxHelp_L("")
  AsmsxHelp_L("    -- Comment")
  AsmsxHelp_L("")
  AsmsxHelp_L("Ada-style single line comment.")
  AsmsxHelp_Commit("2.6. Comments", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("asMSX includes preliminary support for conditional assembly.")
  AsmsxHelp_L("The format of a conditional assembly block is as follows:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("IF condition")
  AsmsxHelp_L("  Instruction")
  AsmsxHelp_L("ELSE")
  AsmsxHelp_L("  Instruction")
  AsmsxHelp_L("ENDIF")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("The condition can be of any type, consistent with C/C++ rules.")
  AsmsxHelp_L("A condition is considered true if evaluation result is non-zero.")
  AsmsxHelp_L("")
  AsmsxHelp_L("If condition is true, asMSX will assemble code that follows `IF`.")
  AsmsxHelp_L("If the condition is false, code after `ELSE` will be assembled.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`ELSE` block is optional for `IF`.")
  AsmsxHelp_L("")
  AsmsxHelp_L("`ENDIF` is mandatory, it closes conditional block.")
  AsmsxHelp_L("")
  AsmsxHelp_L("You can use `INCLUDE` in conditional blocks. Notice that you will receive a")
  AsmsxHelp_L("message that your file has been included, but the conditional block will still")
  AsmsxHelp_L("be effective and the code will not be processed.")
  AsmsxHelp_L("")
  AsmsxHelp_L(":information_source: Current IF nesting limit is 15.")
  AsmsxHelp_L("It may become unlimited in future rewrite.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("IF (computer==MSX)")
  AsmsxHelp_L("  call MSX1_Init")
  AsmsxHelp_L("ELSE")
  AsmsxHelp_L("  IF (computer==MSX2)")
  AsmsxHelp_L("    call MSX2_Init")
  AsmsxHelp_L("  ELSE")
  AsmsxHelp_L("    IF (computer==MSX2plus)")
  AsmsxHelp_L("      call MSX2plus_Init")
  AsmsxHelp_L("    ELSE")
  AsmsxHelp_L("      call TurboR_Init")
  AsmsxHelp_L("    ENDIF")
  AsmsxHelp_L("  ENDIF")
  AsmsxHelp_L("ENDIF")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("In addition, all code, directives and macros will be executed according to")
  AsmsxHelp_L("conditions, this enables creation of the following structures:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("CARTRIDGE=1")
  AsmsxHelp_L("BINARY=2")
  AsmsxHelp_L("format=CARTRIDGE")
  AsmsxHelp_L("IF (format==CARTRIDGE)")
  AsmsxHelp_L("  .page 2")
  AsmsxHelp_L("  .ROM")
  AsmsxHelp_L("ELSE")
  AsmsxHelp_L("  .org 8800h")
  AsmsxHelp_L("  .Basic")
  AsmsxHelp_L("ENDIF")
  AsmsxHelp_L(".START Init")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("There is a limitation on conditional instructions:  ")
  AsmsxHelp_L("`IF` condition, `ELSE` and `ENDIF` must appear on their own **separate lines**.")
  AsmsxHelp_L("They can't be mixed with any other instructions or macros.  ")
  AsmsxHelp_L(":x: The following code will fail with current asMSX:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("IF (variable) nop ELSE inc a ENDIF")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("It should be written as follows:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("IF (variable)")
  AsmsxHelp_L("  nop")
  AsmsxHelp_L("ELSE")
  AsmsxHelp_L("  inc a")
  AsmsxHelp_L("ENDIF")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("`IFDEF` condition could be used to branch code assembly")
  AsmsxHelp_L("using a defined symbol as argument.")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example**:")
  AsmsxHelp_L("")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("IFDEF tests")
  AsmsxHelp_L("  .WAV " + Chr(34) + "Test" + Chr(34) + "")
  AsmsxHelp_L("ENDIF")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("This snippet will generate a WAV file only if the label or variable")
  AsmsxHelp_L("tests was previously defined in the source code.")
  AsmsxHelp_L("")
  AsmsxHelp_L(":warning: **BEWARE!**")
  AsmsxHelp_L("")
  AsmsxHelp_L("- **`IFDEF` will only recognize a label if it is defined before `IFDEF`.**")
  AsmsxHelp_Commit("2.7. Conditional assembly", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("asMSX can use macros. Macros are useful to write little pieces")
  AsmsxHelp_L("of code (snippets). Macros are not functions. When you use a Macro,")
  AsmsxHelp_L("its code will be copied there growing result file's size.")
  AsmsxHelp_L("")
  AsmsxHelp_L("Macros can use parameters to use diferent const values, ")
  AsmsxHelp_L("registers or tag names. All this is possible because")
  AsmsxHelp_L("these macro system only makes a search and replace action of ")
  AsmsxHelp_L("parameter name with the value of that parameter when macro is invoked.")
  AsmsxHelp_Commit("2.8. Macros (version 1.0.1 or above)", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("`MACRO #param, #param,...` Declares a macro. ")
  AsmsxHelp_L("")
  AsmsxHelp_L("`ENDM` Finalizes a macro definition.")
  AsmsxHelp_Commit("2.8.1 Directives associated to macros", "2. Assembly language")

  AsmsxHelp_Begin()
  AsmsxHelp_L("Use this examples in order to know how to declare and use macros")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example: A simple macro**:")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("; Declare Macro to add one to a variable")
  AsmsxHelp_L("m_INC16: MACRO #VARIABLE")
  AsmsxHelp_L("	push	HL")
  AsmsxHelp_L("	ld	HL,#VARIABLE")
  AsmsxHelp_L("	inc	(HL)")
  AsmsxHelp_L("	pop	HL")
  AsmsxHelp_L("ENDM")
  AsmsxHelp_L("")
  AsmsxHelp_L("; Example of use of this macro")
  AsmsxHelp_L("m_INC16 VARNAME")
  AsmsxHelp_L("; RAM variables")
  AsmsxHelp_L("VARNAME byte")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example: A multiparameter macro with variables as parameters**:")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("; Declare Macro to load same patterns and colors bank")
  AsmsxHelp_L(";   to VRAM in Screen 2")
  AsmsxHelp_L("m_LOAD_3BANKS: MACRO #PATTERNS,#COLORS")
  AsmsxHelp_L("	ld 	HL,#PATTERNS")
  AsmsxHelp_L("	ld 	DE,VRM_PAT")
  AsmsxHelp_L("	call 	LOADTOVRAM")
  AsmsxHelp_L("	ld 	HL,#PATTERNS")
  AsmsxHelp_L("	ld 	DE,VRM_PAT+2048")
  AsmsxHelp_L("	call 	LOADTOVRAM")
  AsmsxHelp_L("	ld 	HL,#PATTERNS")
  AsmsxHelp_L("	ld 	DE,VRM_PAT+4096")
  AsmsxHelp_L("	call 	LOADTOVRAM")
  AsmsxHelp_L("	ld 	HL,#COLORS")
  AsmsxHelp_L("	ld 	DE,VRM_COL")
  AsmsxHelp_L("	call 	LOADTOVRAM")
  AsmsxHelp_L("	ld 	HL,#COLORS")
  AsmsxHelp_L("	ld 	DE,VRM_COL+2048")
  AsmsxHelp_L("	call 	LOADTOVRAM")
  AsmsxHelp_L("	ld 	HL,#COLORS")
  AsmsxHelp_L("	ld 	DE,VRM_COL+4096")
  AsmsxHelp_L("	call 	LOADTOVRAM")
  AsmsxHelp_L("ENDM")
  AsmsxHelp_L("; Example of use of this macro")
  AsmsxHelp_L("m_LOAD_3BANKS MYPATTERS, MYCOLORS")
  AsmsxHelp_L("; My own function")
  AsmsxHelp_L("LOADTOVRAM:")
  AsmsxHelp_L("	...")
  AsmsxHelp_L("	ret")
  AsmsxHelp_L("; RAM variables")
  AsmsxHelp_L("MYPATTERS	ds 2048")
  AsmsxHelp_L("MYCOLORS	ds 2048")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example: A multiparameter macro with a register as parameter**:")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("; Declare Macro to create a command to copy a rectangle VRAM VRAM")
  AsmsxHelp_L("m_COPY_SC5: MACRO #X,#Y,#DEST_PAG")
  AsmsxHelp_L("	ld	B,#X ; X")
  AsmsxHelp_L("	ld	C,#Y ; Y")
  AsmsxHelp_L("	ld	IX,VDPCOMDATA")
  AsmsxHelp_L("	ld	A,(IY)")
  AsmsxHelp_L("	ld	(IX+0), A		;SXL")
  AsmsxHelp_L("	ld	(IX+1), 0		;SXH")
  AsmsxHelp_L("	ld	A,(IY+1)")
  AsmsxHelp_L("	ld	(IX+2), A		;SYL")
  AsmsxHelp_L("	ld	A,(IY+4)")
  AsmsxHelp_L("	ld	(IX+3), A		;SYH Page")
  AsmsxHelp_L("	ld	(IX+4), B		;DXL")
  AsmsxHelp_L("	ld	(IX+5), 0		;DXH")
  AsmsxHelp_L("	ld	(IX+6), C		;DYL")
  AsmsxHelp_L("	ld	(IX+7), #DEST_PAG	;DYH Page")
  AsmsxHelp_L("	ld	A,(IY+2)")
  AsmsxHelp_L("	ld	(IX+8), A		;INCXL")
  AsmsxHelp_L("	ld	(IX+9), 0		;INCXH")
  AsmsxHelp_L("	ld	A,(IY+3)")
  AsmsxHelp_L("	ld	(IX+10), A		;INCYL")
  AsmsxHelp_L("	ld	(IX+11), 0		;INCYH")
  AsmsxHelp_L("	ld	(IX+13), 0		;ARG")
  AsmsxHelp_L("	ld	(IX+14), CMDCOPY	; Copy Rectangle VRAM->VRAM")
  AsmsxHelp_L("	ld	HL,VDPCOMDATA		; send to CMD")
  AsmsxHelp_L("	call	_VDPCMD")
  AsmsxHelp_L("ENDM")
  AsmsxHelp_L("; Example of use of this macro")
  AsmsxHelp_L("; In this macro invoke, a register is used as parameter")
  AsmsxHelp_L("	ld	A,(POSITION)")
  AsmsxHelp_L("	add	A,5")
  AsmsxHelp_L("m_COPY_SC5	0,A,1")
  AsmsxHelp_L("; My own function")
  AsmsxHelp_L("_VDPCMD:")
  AsmsxHelp_L("	...")
  AsmsxHelp_L("	ret")
  AsmsxHelp_L("; RAM variables")
  AsmsxHelp_L("POSITION:	byte")
  AsmsxHelp_L("VDPCOMDATA:	ds	15")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example: A multiparameter macro with variable and a const value as parameters**:")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("; Declare Macro to play diferent sounds")
  AsmsxHelp_L("; Parameters are a variable and a const value")
  AsmsxHelp_L("m_SOUND: MACRO #DATASOUND,#DURATION")
  AsmsxHelp_L("	push	HL")
  AsmsxHelp_L("	push	BC")
  AsmsxHelp_L("	ld	C,#DURATION")
  AsmsxHelp_L("	ld	HL,#DATASOUND")
  AsmsxHelp_L("	call	PLAYFX")
  AsmsxHelp_L("	pop	BC")
  AsmsxHelp_L("	pop	HL")
  AsmsxHelp_L("ENDM")
  AsmsxHelp_L("; Example of use of this macro")
  AsmsxHelp_L("m_SOUND SOUND1,30")
  AsmsxHelp_L("; My own function")
  AsmsxHelp_L("PLAYFX:")
  AsmsxHelp_L("	...")
  AsmsxHelp_L("	ret")
  AsmsxHelp_L("; RAM variables")
  AsmsxHelp_L("SOUND1	ds	7")
  AsmsxHelp_L("SOUND2	ds	7")
  AsmsxHelp_L("```")
  AsmsxHelp_L("")
  AsmsxHelp_L("**Example: A multiparameter macro using a parameter as a local tag**:")
  AsmsxHelp_L("```assembly")
  AsmsxHelp_L("; Declare Macro to increments a value until a max value and reset to a value")
  AsmsxHelp_L("m_INCVALUE_MAX_RESET: MACRO #VARIABLE,#MAX,#RESETVALUE")
  AsmsxHelp_L("	ld	A,(#VARIABLE)")
  AsmsxHelp_L("	inc	A")
  AsmsxHelp_L("	cp	#MAX")
  AsmsxHelp_L("	jr	nz,.noreset_#VARIABLE")
  AsmsxHelp_L("	ld	A,#RESETVALUE")
  AsmsxHelp_L(".noreset_#VARIABLE:")
  AsmsxHelp_L("	ld	(#VARIABLE),A")
  AsmsxHelp_L("ENDM")
  AsmsxHelp_L("; Example of use of this macro")
  AsmsxHelp_L("; VARNAME increments until 99 and resets to zero if try to overflow")
  AsmsxHelp_L("m_INCVALUE_MAX_RESET	VARNAME,100,0")
  AsmsxHelp_L("; RAM variables")
  AsmsxHelp_L("VARNAME byte")
  AsmsxHelp_L("```")
  AsmsxHelp_Commit("2.8.2 Macros examples", "2. Assembly language")

EndProcedure
