; Auto-gerado por convert_msxbios.py (descartavel, nao versionado) a partir de
; help/MSXBIOS.CHM (RuMSX, Lex Lechz - lexlechz.at), secao "Documentation & Concepts".
; Conteudo reproduzido como no original.

Structure BiosDocHelpTopic
  Titulo.s
  Grupo.s
  Corpo.s
EndStructure

Global NewList BiosDocHelp_Topics.BiosDocHelpTopic()
Global BiosDocHelp_DataBuilt.b = #False
Global NewList BiosDocHelp_Scratch.s()

Procedure BiosDocHelp_Begin()
  ClearList(BiosDocHelp_Scratch())
EndProcedure

Procedure BiosDocHelp_L(Line.s)
  AddElement(BiosDocHelp_Scratch())
  BiosDocHelp_Scratch() = Line
EndProcedure

Procedure BiosDocHelp_Commit(Titulo.s, Grupo.s)
  Protected Body.s = "", First.b = #True
  ForEach BiosDocHelp_Scratch()
    If Not First : Body + #CRLF$ : EndIf
    Body + BiosDocHelp_Scratch()
    First = #False
  Next
  AddElement(BiosDocHelp_Topics())
  BiosDocHelp_Topics()\Titulo = Titulo
  BiosDocHelp_Topics()\Grupo = Grupo
  BiosDocHelp_Topics()\Corpo = Body
EndProcedure

Procedure BiosDocHelp_BuildData()
  If BiosDocHelp_DataBuilt
    ProcedureReturn
  EndIf
  BiosDocHelp_DataBuilt = #True

  BiosDocHelp_Begin()
  BiosDocHelp_L("Documentation about ESC sequences specific to MSX- and Epson 9-pin printers (to print graphics and control other printer properties):")
  BiosDocHelp_L("")
  BiosDocHelp_L(" ")
  BiosDocHelp_L("")
  BiosDocHelp_L("MSX-Printers")
  BiosDocHelp_L("")
  BiosDocHelp_L("This table lists all control-sequences, known for MSX-printers. This should give an overview, but must not be fully available on all MSX-printers. Control-sequences are typically preceded by ESC (CHR$(27), 1BH). A " + Chr(34) + "n" + Chr(34) + " within the code represents any ASCII-digit from 0-9.")
  BiosDocHelp_L("")
  BiosDocHelp_L("Symbol | Code | Name")
  BiosDocHelp_L("CR | 13 | Carriage return")
  BiosDocHelp_L("LF | 10 | Carriage return + Line feed")
  BiosDocHelp_L("VT | 11 | Vertical tabulator (like LF)")
  BiosDocHelp_L("FF | 12 | Form feed")
  BiosDocHelp_L("ESC, " + Chr(34) + "N" + Chr(34) + " | Font: Courier 1/10" + Chr(34) + " (Pica)")
  BiosDocHelp_L("ESC, " + Chr(34) + "E" + Chr(34) + " | Font: Courier 1/12" + Chr(34) + " (Elite)")
  BiosDocHelp_L("ESC, " + Chr(34) + "Q" + Chr(34) + " | Font: Courier 1/17" + Chr(34) + " (Condensed)")
  BiosDocHelp_L("ESC, " + Chr(34) + "P" + Chr(34) + " | Font: Proportional")
  BiosDocHelp_L("SO | 14 | Double character-width on")
  BiosDocHelp_L("SI | 15 | Double character-width off")
  BiosDocHelp_L("ESC, " + Chr(34) + "!" + Chr(34) + " | Letter Quality on")
  BiosDocHelp_L("ESC, 34 | (ESC, " + Chr(34) + ") Letter Quality off")
  BiosDocHelp_L("ESC, " + Chr(34) + "CS" + Chr(34) + " | Superscript on")
  BiosDocHelp_L("ESC, " + Chr(34) + "Cs" + Chr(34) + " | Superscript off")
  BiosDocHelp_L("ESC, " + Chr(34) + "CU" + Chr(34) + " | Subscript on")
  BiosDocHelp_L("ESC, " + Chr(34) + "Cu" + Chr(34) + " | Subscript off")
  BiosDocHelp_L("ESC, " + Chr(34) + "CI" + Chr(34) + " | Italic on")
  BiosDocHelp_L("ESC, " + Chr(34) + "Ci" + Chr(34) + " | Italic off")
  BiosDocHelp_L("ESC, " + Chr(34) + "CB" + Chr(34) + " | Bold on")
  BiosDocHelp_L("ESC, " + Chr(34) + "Cb" + Chr(34) + " | Bold off")
  BiosDocHelp_L("ESC, " + Chr(34) + "CD" + Chr(34) + " | Double strike on")
  BiosDocHelp_L("ESC, " + Chr(34) + "Cd" + Chr(34) + " | Double strike off")
  BiosDocHelp_L("HT | 9 | Horizontal tabulator")
  BiosDocHelp_L("ESC, " + Chr(34) + "(" + Chr(34) + " | Set a horizontal tab position")
  BiosDocHelp_L("ESC, " + Chr(34) + ")" + Chr(34) + " | Partially delete a horizontal tab position")
  BiosDocHelp_L("ESC, " + Chr(34) + "2" + Chr(34) + " | Delete all horizontal tab positions")
  BiosDocHelp_L("ESC, " + Chr(34) + "O" + Chr(34) + ", " + Chr(34) + "nnn" + Chr(34) + " | Set page-height (lines)")
  BiosDocHelp_L("ESC, " + Chr(34) + "OI" + Chr(34) + ", " + Chr(34) + "nn" + Chr(34) + " | Set page-height(inches)")
  BiosDocHelp_L("ESC, " + Chr(34) + "OS" + Chr(34) + ", " + Chr(34) + "nn" + Chr(34) + " | Perforation-skip setting")
  BiosDocHelp_L("ESC, " + Chr(34) + "OS00" + Chr(34) + " | Perforation-skip off")
  BiosDocHelp_L("ESC, " + Chr(34) + "\" + Chr(34) + ", " + Chr(34) + "nnn" + Chr(34) + " | Right border setting")
  BiosDocHelp_L("ESC, " + Chr(34) + "L" + Chr(34) + ", " + Chr(34) + "nnn" + Chr(34) + " | Left border setting")
  BiosDocHelp_L("ESC, " + Chr(34) + "A" + Chr(34) + " | Line-feed 1/6" + Chr(34))
  BiosDocHelp_L("ESC, " + Chr(34) + "B" + Chr(34) + " | Line-feed 1/9" + Chr(34))
  BiosDocHelp_L("ESC, " + Chr(34) + "T" + Chr(34) + ", " + Chr(34) + "nn" + Chr(34) + " | Line-feed nn/144" + Chr(34))
  BiosDocHelp_L("ESC, " + Chr(34) + "Z" + Chr(34) + ", " + Chr(34) + "nn" + Chr(34) + " | Line-feed nn/216" + Chr(34))
  BiosDocHelp_L("ESC, " + Chr(34) + "[" + Chr(34) + " | Uni-directional printing")
  BiosDocHelp_L("ESC, " + Chr(34) + "]" + Chr(34) + " | Bi-directional printing")
  BiosDocHelp_L("ESC, " + Chr(34) + "p" + Chr(34) + " | PAPER OUT -Detector on")
  BiosDocHelp_L("ESC, " + Chr(34) + "q" + Chr(34) + " | PAPER OUT - Detector off")
  BiosDocHelp_L("ESC, 13 | (ESC, CR) Move printer-head to end-position")
  BiosDocHelp_L("ESC, " + Chr(34) + "@" + Chr(34) + " | Printer reset")
  BiosDocHelp_L("BEL | 7 | Audible beep (buzzer, 0.3s)")
  BiosDocHelp_L("CAN | 24 | Clear printer buffer")
  BiosDocHelp_L("ESC, " + Chr(34) + "G" + Chr(34) + ", " + Chr(34) + "nnn" + Chr(34) + " | Graphic: Density nnn dots/inch")
  BiosDocHelp_L("ESC, " + Chr(34) + "S" + Chr(34) + " | Graphic: Density depending on font")
  BiosDocHelp_L("SOH | 1 | A symbolcode preceding code")
  BiosDocHelp_L("ESC, " + Chr(34) + "X" + Chr(34) + " | Underline on")
  BiosDocHelp_L("ESC, " + Chr(34) + "Y" + Chr(34) + " | Underline off")
  BiosDocHelp_L("BS | 8 | Backstep (1 Character)")
  BiosDocHelp_L("ESC, " + Chr(34) + "r" + Chr(34) + " | Scroll paper back")
  BiosDocHelp_L("ESC, " + Chr(34) + "f" + Chr(34) + " | Scroll paper forward")
  BiosDocHelp_L("ESC, " + Chr(34) + "&" + Chr(34) + " | Toggle International ASCII/Japanese")
  BiosDocHelp_L("ESC, " + Chr(34) + "$" + Chr(34) + " | Toggle International ASCII/Japanese")
  BiosDocHelp_L("")
  BiosDocHelp_L(" ")
  BiosDocHelp_L("")
  BiosDocHelp_L("Epson-Printers")
  BiosDocHelp_L("This section lists only ESC-sequences for 9-pin printers. Available information is not complete yet, but provided as basic reference.")
  BiosDocHelp_L("Symbol | Code | Name")
  BiosDocHelp_L("Setting the page-format")
  BiosDocHelp_L("ESC, " + Chr(34) + "C" + Chr(34) + " | Set page length in lines")
  BiosDocHelp_L("ESC, " + Chr(34) + "C" + Chr(34) + ", NUL | Set page length in inches")
  BiosDocHelp_L("ESC, " + Chr(34) + "N" + Chr(34) + " | Set bottom margin")
  BiosDocHelp_L("ESC, " + Chr(34) + "O" + Chr(34) + " | Cancel bottom margin")
  BiosDocHelp_L("ESC, " + Chr(34) + "Q" + Chr(34) + " | Set right margin")
  BiosDocHelp_L("ESC, " + Chr(34) + "I" + Chr(34) + " | Set left margin")
  BiosDocHelp_L("Moving the print position")
  BiosDocHelp_L("CR | 13 | Carriage return")
  BiosDocHelp_L("LF | 10 | Line feed")
  BiosDocHelp_L("FF | 12 | Form feed")
  BiosDocHelp_L("ESC, " + Chr(34) + "$" + Chr(34) + " | Set absolute horizontal print position")
  BiosDocHelp_L("ESC, " + Chr(34) + "\" + Chr(34) + " | Set relative horizontal print position")
  BiosDocHelp_L("ESC, " + Chr(34) + "J" + Chr(34) + " | Advance print position vertically")
  BiosDocHelp_L("HT | 9 | Tab horizontally")
  BiosDocHelp_L("VT | 11 | Tab vertically")
  BiosDocHelp_L("ESC, " + Chr(34) + "f" + Chr(34) + " | Horizontal/vertical skip")
  BiosDocHelp_L("BS | 8 | Backspace")
  BiosDocHelp_L("Setting the units")
  BiosDocHelp_L("ESC, " + Chr(34) + "0" + Chr(34) + " | Select 1/8-inch line spacing")
  BiosDocHelp_L("ESC, " + Chr(34) + "2" + Chr(34) + " | Select 1/6-inch line spacing")
  BiosDocHelp_L("ESC, " + Chr(34) + "3" + Chr(34) + " | Set n/216-inch line spacing")
  BiosDocHelp_L("ESC, " + Chr(34) + "A" + Chr(34) + " | Set n/72-inch line spacing")
  BiosDocHelp_L("ESC, " + Chr(34) + "1" + Chr(34) + " | Set 7/72-inch line spacing")
  BiosDocHelp_L("ESC, " + Chr(34) + "D" + Chr(34) + " | Set horizontal tabs")
  BiosDocHelp_L("ESC, " + Chr(34) + "B" + Chr(34) + " | Set vertical tabs")
  BiosDocHelp_L("ESC, " + Chr(34) + "b" + Chr(34) + " | Set vertical tabs in VFU channels")
  BiosDocHelp_L("ESC, " + Chr(34) + "f" + Chr(34) + " | Select vertical tab channel")
  BiosDocHelp_L("ESC, " + Chr(34) + "e" + Chr(34) + " | Set fixed tab increment")
  BiosDocHelp_L("Selecting characters")
  BiosDocHelp_L("ESC, " + Chr(34) + "(t" + Chr(34) + " | Assign character table")
  BiosDocHelp_L("ESC, " + Chr(34) + "t" + Chr(34) + " | Select character table")
  BiosDocHelp_L("ESC, " + Chr(34) + "R" + Chr(34) + " | Select an international character-set")
  BiosDocHelp_L("ESC, " + Chr(34) + "&" + Chr(34) + " | Define user-defined characters")
  BiosDocHelp_L("ESC, " + Chr(34) + ":" + Chr(34) + " | Copy ROM to RAM")
  BiosDocHelp_L("ESC, " + Chr(34) + "%" + Chr(34) + " | Select user-defined set")
  BiosDocHelp_L("ESC, " + Chr(34) + "x" + Chr(34) + " | Select NLQ or draft")
  BiosDocHelp_L("ESC, " + Chr(34) + "k" + Chr(34) + " | Select tapeface")
  BiosDocHelp_L("ESC, " + Chr(34) + "P" + Chr(34) + " | Select 10-cpi")
  BiosDocHelp_L("ESC, " + Chr(34) + "M" + Chr(34) + " | Select 12-cpi")
  BiosDocHelp_L("ESC, " + Chr(34) + "g" + Chr(34) + " | Select 15-cpi")
  BiosDocHelp_L("ESC, " + Chr(34) + "p" + Chr(34) + " | Turn proportional mode on/off")
  BiosDocHelp_L("ESC, SP | Set intercharacter space")
  BiosDocHelp_L("ESC, " + Chr(34) + "E" + Chr(34) + " | Select bold font")
  BiosDocHelp_L("ESC, " + Chr(34) + "F" + Chr(34) + " | Cancel bold font")
  BiosDocHelp_L("ESC, " + Chr(34) + "4" + Chr(34) + " | Select italic font")
  BiosDocHelp_L("ESC, " + Chr(34) + "5" + Chr(34) + " | Cancel italic font")
  BiosDocHelp_L("ESC, " + Chr(34) + "!" + Chr(34) + " | Master select")
  BiosDocHelp_L("ESC, " + Chr(34) + "G" + Chr(34) + " | Select double-strike printing")
  BiosDocHelp_L("ESC, " + Chr(34) + "H" + Chr(34) + " | Cancel double-strike printing")
  BiosDocHelp_L("ESC, " + Chr(34) + "-" + Chr(34) + " | Turn underline on/off")
  BiosDocHelp_L("ESC, " + Chr(34) + "S" + Chr(34) + " | Select superscript/subscript printing")
  BiosDocHelp_L("ESC, " + Chr(34) + "T" + Chr(34) + " | Cancel superscript/subscript printing")
  BiosDocHelp_L("SI | 15 | Select condensed printing")
  BiosDocHelp_L("ESC, SI | Select condensed printing")
  BiosDocHelp_L("DC2 | Cancel condensed printing")
  BiosDocHelp_L("SO | 14 | Select double-width printing (one line)")
  BiosDocHelp_L("ESC, SO | Select double-width printing (one line)")
  BiosDocHelp_L("DC4 | Cancel double-width printing")
  BiosDocHelp_L("ESC, " + Chr(34) + "W" + Chr(34) + " | Turn double-width printing on/off")
  BiosDocHelp_L("ESC, " + Chr(34) + "w" + Chr(34) + " | Turn double-width printing on/off")
  BiosDocHelp_L("Control-code character printing")
  BiosDocHelp_L("ESC, " + Chr(34) + "6" + Chr(34) + " | Enable printing of upper control-codes")
  BiosDocHelp_L("ESC, " + Chr(34) + "7" + Chr(34) + " | Enable upper control-codes")
  BiosDocHelp_L("ESC, " + Chr(34) + "l" + Chr(34) + " | Enable printing of control-codes")
  BiosDocHelp_L("ESC, " + Chr(34) + "m" + Chr(34) + Chr(34) + " | Select printing of upper control-codes")
  BiosDocHelp_L("Mechanical control")
  BiosDocHelp_L("ESC, " + Chr(34) + "EM" + Chr(34) + " | Control paper loading/ejecting")
  BiosDocHelp_L("ESC, " + Chr(34) + "U" + Chr(34) + " | Turn unidirectional mode on/off")
  BiosDocHelp_L("ESC, " + Chr(34) + "<" + Chr(34) + " | Unidirectional mode (one line)")
  BiosDocHelp_L("BEL | 7 | Beeper")
  BiosDocHelp_L("ESC, " + Chr(34) + "8" + Chr(34) + " | Disable paper-out detector")
  BiosDocHelp_L("ESC, " + Chr(34) + "9" + Chr(34) + " | Enable paper-out detector")
  BiosDocHelp_L("ESC, " + Chr(34) + "s" + Chr(34) + " | Select low-speed mode")
  BiosDocHelp_L("Printing color and graphics")
  BiosDocHelp_L("ESC, " + Chr(34) + "*" + Chr(34) + " | Select bit image")
  BiosDocHelp_L("ESC, " + Chr(34) + "?" + Chr(34) + " | Reassign bit-image mode")
  BiosDocHelp_L("ESC, " + Chr(34) + "K" + Chr(34) + " | Select 60-dpi graphics")
  BiosDocHelp_L("ESC, " + Chr(34) + "L" + Chr(34) + " | Select 120-dpi graphics")
  BiosDocHelp_L("ESC, " + Chr(34) + "Y" + Chr(34) + " | Select 120-dpi, double-speed graphics")
  BiosDocHelp_L("ESC, " + Chr(34) + "Z" + Chr(34) + " | Select 240-dpi graphics")
  BiosDocHelp_L("ESC, " + Chr(34) + "^" + Chr(34) + " | Select 60/120-dpi, 9-pin graphics")
  BiosDocHelp_L("ESC, " + Chr(34) + "r" + Chr(34) + " | Select printing color")
  BiosDocHelp_L("Printing bar codes")
  BiosDocHelp_L("ESC, " + Chr(34) + "(B" + Chr(34) + " | Bar code setup and print")
  BiosDocHelp_L("Data and memory control")
  BiosDocHelp_L("ESC, " + Chr(34) + "@" + Chr(34) + " | Initialize printer")
  BiosDocHelp_L("CAN | 24 | Cancel line")
  BiosDocHelp_L("DEL | Delete last character in buffer")
  BiosDocHelp_L("DC1 | Select printer")
  BiosDocHelp_L("DC3 | Deselect printer")
  BiosDocHelp_L("ESC, " + Chr(34) + "#" + Chr(34) + " | Cancel MSB control")
  BiosDocHelp_L("ESC, " + Chr(34) + "=" + Chr(34) + " | Set MSB to 0")
  BiosDocHelp_L("ESC, " + Chr(34) + ">" + Chr(34) + " | Set MSB to 1")
  BiosDocHelp_L("Deleted commands")
  BiosDocHelp_L("ESC, " + Chr(34) + "j" + Chr(34) + " | Reverse paper feed")
  BiosDocHelp_L("ESC, " + Chr(34) + "i" + Chr(34) + " | Select immediate print mode")
  BiosDocHelp_Commit("MSX-BIOS: Printer ESC sequences", "Documentacao")

  BiosDocHelp_Begin()
  BiosDocHelp_L("* This document concerns MSXes from 1. Note turboR was not released when this document was authored.")
  BiosDocHelp_L("")
  BiosDocHelp_L("2.2.5 Software Reset")
  BiosDocHelp_L("")
  BiosDocHelp_L("If you reset an MSX by jumping to 0 address (this is called a software reset) you might disable kanji ROM. Device enable function is the cause of this symptom.")
  BiosDocHelp_L("")
  BiosDocHelp_L("Device enable is a name of function to prevent bus conflict. For example, if you connect an external kanji ROM to a MSX equipped with internal kanji ROM, this means two devices are stuck into one I/O port, therefore causing conflicts between signals coming from these kanji ROMs, and in worst case, MSX itself will crush. To prevent this, F5H of I/O port is supplied as device enable function, and it works as follows.")
  BiosDocHelp_L("")
  BiosDocHelp_L("When you turn power of an MSX on, MSX assumes its internal kanji ROM as disconnected, and BIOS checks kanji ROM status. Since internal kanji ROM is disconnected, if MSX detects a kanji ROM presence, the detected kanji ROM should be an external one.")
  BiosDocHelp_L("")
  BiosDocHelp_L("If no external kanji ROM was found, MSX writes 1 to bit 0 of F5H I/O port and enables internal kanji ROM (refer to page 391 of MSX2 Technical Handbook - I don't know correspondent page no. in English version;). These procedures so far allow you to insert an external kanji ROM into an MSX with internal kanji ROM. RS-232C is supported by similar function too.")
  BiosDocHelp_L("")
  BiosDocHelp_L("But, if a program jumps to 0 address through commands like JP 0H (C3 00 00), MSX will go to the rountine to check kanji ROM status, while assuming internal kanji ROM is connected. When this happens, MSX thinks its internal kanji ROM as external one, and disconnects it. There is no problem if an MSX goes to the routine to check external device at the time of power on and pressing a reset button, but if you want to let a program to reset, in another word, if you want to jump to 00H, you must perfrom some preventive measure. Practical method is as follows;")
  BiosDocHelp_L("")
  BiosDocHelp_L("* If you want to let a software to reset, execute the following.")
  BiosDocHelp_L("")
  BiosDocHelp_L("LD   A,00H")
  BiosDocHelp_L("OUT (F5H),A")
  BiosDocHelp_L("JP  0H")
  BiosDocHelp_L("")
  BiosDocHelp_L("Basically, as MSX2 Technical Handbook insists, users are forbidden to read or write F5H of I/O, so this is not a very appreciated method, but there are no other means to abort the problem. Note even this procedure cannot solve misguided execution; in that case, it means the I/O F5H of your MSX operates dissimilar to other MSXes. (This is possible to happen, since direct accesses to F5H are not in MSX developer's mind)")
  BiosDocHelp_L("")
  BiosDocHelp_L("Note, with MSX2+, external devices are always disconnected by writing 0 into F5H I/O, so you can safely write 0.")
  BiosDocHelp_L("")
  BiosDocHelp_L("Also, since MSX2+, you can check reset status. Use added BIOS to do so.")
  BiosDocHelp_L("")
  BiosDocHelp_L("* If you want to check reset status with MSX2+, do as follows.")
  BiosDocHelp_L("")
  BiosDocHelp_L("CALL 017AH")
  BiosDocHelp_L("")
  BiosDocHelp_L("After doing this, if bit 7 of returned A register is standing, you can learn that MSX was restarted by JP 0H reset (software reset). If the bit 7 is not standing, it means an MSX was resetted by hardware reset. I guess this function was added because if software cannot detect between hardware reset and software reset, many troubles are likely to happen. In fact, a hardware to check reset is added to F4H of I/O, and inside of the BIOS here reads and write the F4H port.")
  BiosDocHelp_L("")
  BiosDocHelp_L("To safely use this function, you must let a software which is going to execute software reset to write a value. Use a BIOS which was newly implemented since MSX2+, too.")
  BiosDocHelp_L("")
  BiosDocHelp_L("* If you want to reset an MSX2+, do as follows.")
  BiosDocHelp_L("")
  BiosDocHelp_L("CALL 017AH  ; Write current reset status into A register.")
  BiosDocHelp_L("OR   80H    ; Set reset flag.")
  BiosDocHelp_L("CALL 017DH  ; Write a new value.")
  BiosDocHelp_L("JP   0H     ; Jump to address 0.")
  BiosDocHelp_L("")
  BiosDocHelp_L("Note, there is no way to detect between software reset and hardware reset with MSX1 and MSX2.")
  BiosDocHelp_Commit("Reset", "Documentacao")

EndProcedure
